### ISSUE TITLE
Feature Request- Disguise as Target

### ISSUE THREAD

**Issue by NightScythe1** [elBukkit/MagicPlugin#1083]
Looking to make a spell that will disguise a player/caster as their target.
Currently this is possible using the Command action and typing:
```
          - class: Command
          command: disguiseplayer @p @t
          console: true
```
however, this means normal magic parameters such as Undo cannot apply to it, and players may get stuck in disguise if the spell cancels.
It also means it cannot be used on players as you'd need a different command-
```
          - class: Command
          command: disguiseplayer @p player @t
          console: true
```
So i wanted to ask if a little integration fix with Libsdisguises was possible, to allow 'target' as an option for the 'type:' in the Magic 'Disguise' action. Thanks for reading!

**Comment by NightScythe1** [comment]
ah awesome, thanks! i'll give it a test as soon as i'm home

**Comment by NightScythe1** [comment]
doesn't seem to be working unfortunately- My spell is set to use a selector to find the target & then changecontext to disguise the caster. I *may* have formatted it wrong? here's the spell-
```
disguise_self:
    name: Disguise Self
    actions:
      cast:
      - class: EntitySelect
        actions:
          - class: ChangeContext
            target_self: true
            actions:
              - class: Message
                message: TEST
              - class: Disguise
                disguise_target: target
    parameters:
        disguise_target: target
        range: 48
        target_type: LivingEntity
        target: other
        hitbox: true

```
