### ISSUE TITLE
[Bug] Can't change the slot to equip with Eqiup Action

### ISSUE THREAD

**Issue by tororo1066** [elBukkit/MagicPlugin#1091]
Try spell:
```yml
test_slash:
  creator: tororo_1066
  creator_id: b4ec7d4f-4b7e-43c1-bb7d-83e1dd29e591
  name: My New Spell
  description: Damage Your Target
  icon: stick
  actions:
    cast:
      - class: ArmorStandProjectile
        speed: 0
        right_arm_item: potion{CustomModelData:11}:#00B3FF
        spawn:
          - class: Delay
            delay: 50
          - class: Equip
            item: potion{CustomModelData:12}:#00B3FF
            slot: main_hand
          - class: Delay
            delay: 50
          - class: Equip
            item: potion{CustomModelData:13}:#00B3FF
            slot: main_hand
```
Error:
![image](https://user-images.githubusercontent.com/71592738/179671039-8fe7ae9f-f8f0-4897-bf4e-3ca4c22d21f0.png)
