### ISSUE TITLE
[Bug] Display name of Wand Item, Affects display name of Spells. + Lore on spells not working

### ISSUE THREAD

**Issue by Ash10744** [elBukkit/MagicPlugin#1094]
Version: Magic-10.8.1
Server Version:
![image](https://user-images.githubusercontent.com/16086663/181781647-a79e6271-8990-4f0d-88dd-3969c6e64a06.png)

Config of Wand:
```
# This is the key name of this wand
# It must be unique across the server, and is used in commands such as /wand and /mgive to refer to this wand.
Fluffys_Cake:
  # These track who created what spells, you can remove them if you want
  creator: Ash10744
  creator_id: 1ca75b77-6280-4eb3-8c86-58cf8ff13d8e
  # Name and description may be added here and will appear in lore for this wand.
  name: Fluffos Cake
  description: Don't eat it
  display_name: §8[§5Unique§d+§8] §5Fluffos Cake
  lore:
    - §8―――――――――――――――――――――――§d―――§8―――――――――――――――――――――――
    - §eA Magical Staff of the Fluffy
    - §8―――――――――――――――――――――――§d―――§8―――――――――――――――――――――――
    - '§cMana: §3$mana'
    - '&CCurrent Spell: §f$spell'
    - §8―――――――――――――――――――――――§d―――§8―――――――――――――――――――――――
  # Inherit from the base_wand template to get basic wand functionality
  # Such as spell inventory and key bindings
  # Other options include: basic_wand, base_bound, base_magic
  inherit: base_wand
  # Choose an icon, this is the item the wand will appear as
  icon: Crossbow{CustomModelData:10010}
  # Give the wand some mana for casting
  mana_max: 5000
  mana: 5000
  # The wand regenerates this amount of mana every second
  mana_regeneration: 5000
  # Give the wand some spells to cast
  spells: []
```

Config of Spell:
```
# This is the key name of this spell
# It must be unique across the server, and is used in configs and commands such as /mage, /wand and /mgive
# to refer to this spell.
spark:
  # These track who created what spells, you can remove them if you want
  creator: Ash10744
  creator_id: 1ca75b77-6280-4eb3-8c86-58cf8ff13d8e
  # Name and description may be added here and will appear in lore for this spell.
  name: §8[§dSpell§8] §6Spark
  description: The user conjures forth a spark to cause light.
  lore:
  - §8test
  - '§8%xp%'
  # Choose an icon, used when showing this spell in a wand inventory.
  icon: meteor
  category: combat
  worth: 0
  earns: 0
  cooldown: 10
  upgrade: true
  actions:
      cast:
      -  class: EntitySelect
         actions:
         -  class: CustomProjectile
  effects:
      cast:
      -  class: EffectSingle
         sound: entity_generic_burn
         location: origin
         color_override: color_override
         effectlib:
           class: ConeEffect
           particle: flame
           lengthGrow: 0.1
           radiusGrow: 0.003
           updateLocations: false
           updateDirections: false
  parameters:
      allow_max_range: true
      velocity: 200
      range: 8
      hitbox: true
      target_type: Damageable
      player_damage: 2
      entity_damage: 4
      target_breakables: 1
      cooldown: 15 seconds
      reorient: false
      destructible: solid
      destructible_durability: 50
      break_durability: 2
      undo: 10000
  costs:
      mana: 

```

Bug Proof:
The Spell with the display name on the wand:
![image](https://user-images.githubusercontent.com/16086663/181782334-c2dd45e9-c8d8-4ace-b51e-09e0e993e26c.png)

The spell without a display name on a wand:
![image](https://user-images.githubusercontent.com/16086663/181782375-5c4abc28-b47c-4a21-8232-930a83f3c924.png)

I also found it works fine if the spell is in my inventory not on my Hotbar. So I believe this to be a bug.

The lore on the spell doesn't also display properly I am unsure if I have done something wrong but it won't display properly despite the wand I am using.
