### ISSUE TITLE
CheckBlock & ModifyBlock Block States parameters?

### ISSUE THREAD

**Issue by NightScythe1** [elBukkit/MagicPlugin#1113]
I'm making some ritualistic spells that check and modify the surrounding environment. One of which, I'm trying to make it check around the Player if there are **Lit Candles** and if so, extinguish them. However, the most I can do is check for **any candles** and remove/replace them. I'm not sure if it's possible already, but would it be possible to allow use of Block States in these actions. E.G.
```
    - class: CheckBlock
      allowed: amethyst_block
      blockstates:
         - lit: true
         - candles: 4
```
and the possibility of modifying a block's state without changing the block itself would be perfect as well. For example-
```
    - class: ModifyBlock
      blockstates:
         - lit: false
```
apologies if this is impossible or already available, as i'm having a hard time figuring it out. thanks!
