### ISSUE TITLE
[BUG] Variables not working on Selector action

### ISSUE THREAD

**Issue by shareacoke** [elBukkit/MagicPlugin#1119]
Hi, I have recently upgraded the magic plugin from an older version and, as expected, some spells needed some fixing and most of them are okay, but I think I found a common error on my config when reloading that I don't understand why it worked before, but now it does not.

I used to have several selectors inherit from one that acts as a base for the rest, so I just have to change a few slots in parameters section in the inherit ones, and they will be good to go. I made a simpler example - which may not have sense in a minecraft server, it's just made up, so you can see the behavior I am talking about.

```
missile_menu:
  icon: book
  actions:
    cast:
    - class: Selector
      options:
      - cast_spell: $opt
        name: $opt_name
        slot: 4
        cost: 1
  parameters:
    target: self
    title: Cast a Missile
    opt_name: "&3Do you want to cast a missile?"
    opt: missile

heal_menu:
  inherit: missile_menu
  parameters:
    title: Cast a healing speel
    opt_name: "&3Do you wan to cast a healing speel?"
    opt: heal
```

Those spells work on older versions (in this example version 8.7.1).

![selector with variables version 8](https://user-images.githubusercontent.com/37221955/193414353-9f4a1dc3-5f01-4670-bee2-218cc7dfb80f.gif)

But they do not work on 10.8.3

![selector with variables version 10](https://user-images.githubusercontent.com/37221955/193414424-59daf052-fc51-4b2e-b522-046443821c3f.gif)

Is it a bug? Or was that discontinued for a reason? It could be intentional like if it was not working for different game versions or so. If it was not a wanted/intentional change/feature, could it come back?

Also, thank you in advance.
