### ISSUE TITLE
Summoned mobs didin't follow had no AI and target_types are broken. What i can do?

### ISSUE THREAD

**Issue by vajuvung** [elBukkit/MagicPlugin#1123]
Hi

So my minions no longer follow me  and spells that has target_types no longer typed mobs. What i can do?

Spells:
summon
```
florasummon:
  icon: gold_nugget{CustomModelData:10}
  icon_disabled: barrier
  quick_cast: true
  toggle: undo
  hidden: true
  locked: true
  actions:
    cast:
    - class: SpawnEntity
      cast_interval: 1000
      interval: 1000
      interact_spell: floramenu
      tamed: true
      entity_attributes:
        generic_attack_damage: "(luck * 0.25) + 4"
        generic_movement_speed: "0.3"
      brain:
        goals:
        - type: trigger
          trigger: attack
          priority: 1
          goals:
            - melee_attack
        - type: follow_owner
          priority: 2
        - type: look_at_player
          priority: 3
        targets:
        - owner_hurt_target
        - owner_hurt_by_target
      triggers:
        attack:
          cast:
            Podstawowy_atak: 20
    - class: Aggro
    - class: Delay    
  parameters:
    target: self
    health: "health_max * 5"
    entity_undo: true
    helmet: iron_helmet
    type: skeleton
    name: Minion
    model: maskotka
    ```
    And attack spell
    ```
    Podstawowy_atak:
  name: Podstawowy atak
  icon: iron_nugget{CustomModelData:21}
  description: Wystrzeluje pocisk zadający obrazenia (4 Obrażeń) 
  icon_disabled: barrier
  locked: true
  hidden: true
  actions:
      cast: 
      - class: ConeOfEffect
        fov: 0.5
        target: other_entity
        target_count: 1
        actions:
        - class: Repeat
          repeat: 1
          actions:
          - class: Delay
            delay: 25
          - class: CustomProjectile
            range: "90 + knockback * 5"
            actions:
            - class: UpdateParameters
              actions:
              - class: Damage
                damage_type: projectile
  effects:
    cast:
    - sound: item_firecharge_use
      location: origin
      sound_volume: 1.5
      sound_pitch: 2.5
    tick: 
    - particle: redstone
      particle_count: 1
      color: "FFFFFF"
      particle_offset_x: 0.3
      particle_offset_y: 0.3
      particle_offset_z: 0.3
      location: target
    - particle: redstone
      particle_count: 1
      color: "FFFFFF"
      particle_offset_x: 0.15
      particle_offset_y: 0.15
      particle_offset_z: 0.15
      location: target
  parameters:
    velocity: 90
    hitbox: true
    target_types: zombie,husk,blaze,cave_spider,creeper,drowned,elder_guardian,ender_dragon,enderman,endermite,evoker,evoker_fangs,ghast,giant,guardian,illusioner,magma_cube,phantom,piglin,piglin_brute,pillager,ravager,shulker,skeleton,slime,spider,strider,trident,vex,vindicator,witch,wither,wither_skeleton,wither_skull,zoglin,zombie_villager,zombified_piglin,pig,sheep,cow,chicken,bee,horse
    ignore_name: Minion
    tick_size: 0.15
    hitbox_size: 0.1
    damage: "sharpness + attack_damage - target_luck * 0.5"
    min_damage: 1
    cooldown: "1000 * (1 - sweeping / 10)"
    ```
