### ISSUE TITLE
Drop Rule Exploit (?)

### ISSUE THREAD

**Issue by NightScythe1** [elBukkit/MagicPlugin#1137]
Working on making custom drops-
I'm trying to replace emerald ore's drop with my own custom drop 'Mystite' with this in a World config-
```
  block_break:
    mystite_ore:
      class: Drop
      types:
        - emerald_ore
        - deepslate_emerald_ore
      items:
        mystite: 1
```
It works, however-
A) I'm unsure how to 'replace' the drop- I can only add the Mystite drop, but it still drops an emerald.
B) There's a duplication exploit here- Players can use Silk Touch on the Ore and simply keep replacing it over and over again to get the added drop. Unless I'm missing a tag to prevent this?
