### ISSUE TITLE
No ranged_attack AI?

### ISSUE THREAD

**Issue by NightScythe1** [elBukkit/MagicPlugin#1140]
Trying to make a spell to summon a mob with the AI to shoot a bow, I think the AI for this is "ranged_attack" by using [this page for reference,](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_ranged_attack) but I can't seem to get this working in Magic? 

```
    entity_parameters:
          chestplate: iron_chestplate
          helmet: iron_helmet
          item: bow
          health: 40
          brain:
            goals:
              - type: ranged_attack
                priority: 1
              - type: follow_owner
                priority: 2
              - type: random_stroll
                priority: 3
            targets:
              - owner_hurt_target
              - owner_hurt_by_target
              - hurt_by_target

```
It's also not present in [this file](https://github.com/elBukkit/MagicPlugin/blob/e43d07061fd99cbbabe535cbf6f7a8936ff4f54c/CompatibilityLib/common/src/main/java/com/elmakers/mine/bukkit/mob/GoalType.java) (if i'm even looking in the right place)
