### ISSUE TITLE
Armor Attribute being read wrong

### ISSUE THREAD

**Issue by NightScythe1** [elBukkit/MagicPlugin#1162]
For some reason, the Armor attribute in magic seems to be registering incorrectly when used in classes/spells.
I have a class that has a 'protection' depending on a player's armour amount:
```
  protection:
    necromancy_damage: armor/200
```
The intended function would be a player in full Diamond (20 armor points) gets a 0.2 reduction. But the 'armor' value here only seems to register from the last time the armor value _changed_. Aka, it reads it when a player equips/unequips armour, but does not catch the new value caused by the value that triggered it. 
**E.G:** 

a player with _0 armour_ who puts on boots, will still register as _0 armor_, but if they then put on leggings, it now triggers and registers that the player has boots on, and updates the value to _3 armor_ but misses the leggings. if a player then equipped a chestplate, it would trigger and register the boots AND the leggings, updating it to _9 armor_, but missing the chestplate.

the same issue occurs when un-equipping armor. Taking off any armour will update it again to the last known armor value, but doesn't catch the unequip. meaning if a player equipped, then unequipped a chestplate, they would still be read as *8 armor* by magic, until they equip/unequip something else.

The strange part is that using "/mage attribute armor" still shows the correct, expected value. The issue is only apparent when using this 'armor' attribute in a spell/class protection as i showed above.

Here's a class and spell if you'd like to try reproducing it. Just enable the class for yourself, equip various armor levels, and cast the spell on yourself. (I changed the custom damage type to just Magic here, for easier time reproducing it.)
```
attribute_bug_spell:
  actions:
    cast:
    - class: Damage
  parameters:
    target: self
    damage: 10
    damage_type: magic
```

```
attribute_bug_class:
  passive: true
  protection:
    magic: armor/200
```
