### ISSUE TITLE
Brain remove_default_goals not working

### ISSUE THREAD

**Issue by Remodactyl** [elBukkit/MagicPlugin#1163]
setting remove_default_goals to false has no effect on mobs with the brain property specified.
these mobs will still lose any and all AI that would otherwise control them.
adding any type of functionality to Brain now comes at the inevitable cost of losing all Vanilla AI.

**Comment by NathanWolf** [comment]
Are you on 1.19.3?

I did have to change something related to removing default goals .. but I thought if anything it would've broken the ability to remove them, not the other way around.

**Comment by NathanWolf** [comment]
Can you show me your mob configs?

I just tested using the following two mobs- `scared` keeps all the default cat goals, and `scared2` does not, so it seems to be working for me. Tested on 1.19.3

```
scared:
  type: cat
  brain:
    remove_default_goals: false
    goals:
    - type: panic

scared2:
  type: cat
  brain:
    remove_default_goals: true
    goals:
      - type: panic
```
