### ISSUE TITLE
Minion Spammer

### ISSUE THREAD

**Issue by vajuvung** [elBukkit/MagicPlugin#1164]
Hi. So my problem is my minion just spam spells and will be okey if minion has mana but i can't find mana or something like that. Is possible to add mana to minion?
```
florasummon:
  icon: gold_nugget{CustomModelData:10}
  icon_disabled: barrier
  quick_cast: true
  toggle: undo
  hidden: true
  locked: true
  interval: 1000
  actions:
    cast:
    - class: SpawnEntity
      interval: 1000
      tamed: true
      mage: Gracz
      entity_attributes:
        generic_attack_damage: "(luck * 0.25) + 4"
        generic_movement_speed: "0.3"
      brain:
        goals:
        - type: trigger
          trigger: attack
          priority: 1
          goals:
            - melee_attack
        - type: follow_owner
          priority: 2
        - type: look_at_player
          priority: 3
        targets:
        - owner_hurt_target
        - owner_hurt_by_target
      triggers:
        attack:
          cast:
            explozja_ciemnosc_1: 20
            explozja_ogien_1: 20
            explozja_piorun_1: 20
            explozja_swiatlo_1: 20
            explozja_trucizna_1: 20
            explozja_wiatr_1: 20
            explozja_woda_1: 20
            explozja_ziemia_1: 20
            kolce_ciemnosc_1: 20
            kolce_ognia_1: 20
            kolce_piorun_1: 20
            kolce_swiatlo_1: 20
            kolce_trucizna_1: 20
            kolce_wiatr_1: 20
            kolce_woda_1: 20
            kolce_ziemia_1: 20
            lancuch_ciemnosc_1: 20
            lancuch_ogien_1: 20
            lancuch_piorun_1: 20
            lancuch_swiatlo_1: 20
            lancuch_trucizna_1: 20
            lancuch_wiatr_1: 20
            lancuch_woda_1: 20
            lancuch_ziemia_1: 20
            laser_ciemnosc_1: 20
            laser_ogien_1: 20
            laser_piorun_1: 20
            laser_swiatlo_1: 20
            laser_trucizna_1: 20
            laser_wiatr_1: 20
            laser_woda_1: 20
            laser_ziemia_1: 20
            lewitacja_ciemnosc_1: 20
            lewitacja_ogien_1: 20
            Podstawowy_atak: 20    
  parameters:
    target: self
    health: "health_max * 5"
    entity_undo: true
    helmet: iron_helmet
    type: skeleton
    name: Minion
    model: maskotka
```
