### ISSUE TITLE
CheckTriggers Improvements to add the same functionality as CheckRequirements

### ISSUE THREAD

**Issue by I0nTech** [elBukkit/MagicPlugin#1165]
CheckTrigger currently can only check for a single trigger without any trigger requirements 
```
CheckTrigger:
  trigger: sometrigger
```

Unlike CheckRequirements, where requirements can be defined like:
```
Class: CheckRequirements
  requirements:
      - variables:
         - variable: somevariable
           min: 0.5
         - variable: anothervariable
            max: 3
``` 

Suggestion: Add CheckTriggers or update CheckTrigger to check for triggers like
```
Class: CheckTriggers
    triggers:
      - trigger: damage
        damage_types: physical,projectile,magic,explosion
        min_health: 2
      - trigger: left_click
```
to allow for more complex spell behaviors
