### ISSUE TITLE
ModifyAttribute can deactivated wand after change modify attribute

### ISSUE THREAD

**Issue by vajuvung** [elBukkit/MagicPlugin#1168]
https://www.youtube.com/watch?v=jR5bhMsA_48

So my spell inventory get closed every time when attribute is cahnged. How i can fix it?

Spell [this is passive]
```
Judgment_blood_end:
  passive: true
  triggers:
    - trigger: damage_dealt
  actions:
    cast:
    - class: ModifyAttribute
      attribute: style
      modify_target: class
      value: "x + 1"
    - class: Delay
      delay: 20
#    - class: CheckInventory
#      item: ksiazka_sss
#      slot: 11
    - class: CheckRequirements
      requirements:
      - attributes:
        - attribute: style
          min: 4
          max: 6
      actions:
      - class: Message
        message: desmo
        message_type: action_bar
      - class: PlaySound
        sound: sound.custom.desmo

    - class: CheckRequirements
      requirements:
      - attributes:
        - attribute: style
          min: 10
          max: 12
      actions:
      - class: Message
        message: Crazy
        message_type: action_bar
      - class: PlaySound
        sound: sound.custom.crazy

    - class: CheckRequirements
      requirements:
      - attributes:
        - attribute: style
          min: 14
          max: 16
      actions:
      - class: Message
        message: Basad
        message_type: action_bar
      - class: PlaySound
        sound: sound.custom.badas

    - class: CheckRequirements
      requirements:
      - attributes:
        - attribute: style
          min: 19
          max: 21
      actions:
      - class: Message
        message: Apocalyptic
        message_type: action_bar
      - class: PlaySound
        sound: sound.custom.apocalyptic

    - class: CheckRequirements
      requirements:
      - attributes:
        - attribute: style
          min: 24
          max: 26
      actions:
      - class: Message
        message: SAVAGE!
        message_type: action_bar
      - class: PlaySound
        sound: sound.custom.savage

    - class: CheckRequirements
      requirements:
      - attributes:
        - attribute: style
          min: 29
          max: 31
      actions:
      - class: Message
        message: SICK SKILLS!!
        message_type: action_bar
      - class: PlaySound
        sound: sound.custom.sick_skills

    - class: CheckRequirements
      requirements:
      - attributes:
        - attribute: style
          min: 34
          max: 36
      actions:
      - class: Message
        message: SMOKING SEXY STYLE!!!
        message_type: action_bar
      - class: PlaySound
        sound: sound.custom.smoking_sexy_style

    - class: CheckRequirements
      requirements:
      - attributes:
        - attribute: style
          min: 38
          max: 40
      actions:
      - class: ModifyAttribute
        attribute: style
        value: 1
      - class: Command
        command: castp @pn JCE
        console: true
  parameters:
    target: self
    ```
