### ISSUE TITLE
Attributes giving arbitrary/irrational values

### ISSUE THREAD

**Issue by NightScythe1** [elBukkit/MagicPlugin#1185]
![2023-03-03_02 42 07](https://user-images.githubusercontent.com/18646617/222618173-6fa8235e-8f9d-4dd7-8d0d-3579b351649a.png)
```
tenet_oceanic:
  name: Oceanic Tenet
  description: Spend time in Water. Avoid leaving the water.
  triggers:
    - trigger: interval
      interval: 10000
  actions:
    cast:
    - class: CheckBlock
      allowed: water
      source_location: feet
      actions:
        - class: ModifyAttribute
          attribute: deity_favour
          bypass_undo: true
          value: "x+0.6"
      fail:
        - class: CheckRequirements
          requirements:
            - attributes:
              - attribute: deity_favour
                min: 1
          actions:
            - class: ModifyAttribute
              attribute: deity_favour
              bypass_undo: true
              value: "x-0.2"
  parameters:
    target: self
```
when using the above spell, the player should gain 0.6 attribute for every 10 seconds spent in water, and lose 0.2 attribute every 10 seconds out of water, but it seems that it's not adding/removing exactly 0.2 or 0.6 and over time it winds up with these strange values. The 0.6 and 0.2 are the only things able to change/alter this attribute right now
