### ISSUE TITLE
Help making a MagicSpells spell

### ISSUE THREAD

**Issue by gedo213214** [elBukkit/MagicPlugin#1187]
I want to make a spell that, when the enemy is stunned, stuns me for the same number of seconds, can you correct the code?

```
Stun:
    spell-class: ".targeted.StunSpell"
    duration: 10
    interval: 10
    hit-self: true
Kagemane_no_Jutsu:
    spell-class: ".targeted.HomingMissileSpell"
    start-forward-offset: 0
    cast-item: stick
    cooldown: 15
    max-duration: 10
    projectile-velocity: 5
    hug-surface: true
    y-offset: 0
    particle-name: footstep
    particle-count: 5
    particle-speed: 5
    particle-horizontal-spread: 0.1
    particle-vertical-spread: 0.05
    cost:
        - mana 25
    hit-players: true
    hit-non-players: true
    hit-ground: false
    hit-self: true
    spell: Stun
 ```
