### ISSUE TITLE
CheckInventory not working on Bows 

### ISSUE THREAD

**Issue by NightScythe1** [elBukkit/MagicPlugin#1191]
Can't use checkinventory to check for a bow:
```
bow_arrow:
  triggers:
    - launch
  actions:
      cast:
      - class: CheckInventory
        slot: mainhand
        item: snowball
        actions:
          - class: Retarget
            target: none
            actions:
              - class: Projectile
```
This is supposed to check if the player has a bow in their hand & launch an arrow if they do. It doesn't work, but will work if checking for other items like snowballs
