### ISSUE TITLE
Attributes applied to mobs not functioning properly?

### ISSUE THREAD

**Issue by NightScythe1** [elBukkit/MagicPlugin#1217]
```
dragon_stat_randomiser:
  icon: enchanted_book
  actions:
    cast:
    - class: CheckRequirements
      requirement:
        attribute:
          attribute: dragon_generated
          max: 0.5
      actions:
        - class: ModifyEntity
          mage:
            attributes:
              dragon_generated: 1
              health_dragon: ceil(rand(0,12))
              defence_dragon: ceil(rand(0,12))
              power_dragon: ceil(rand(0,12))
              speed_dragon: ceil(rand(0,12))
              agility_dragon: ceil(rand(0,12))
  parameters:
    bypass_undo: true
    target: other
```

the following spell is intended to apply a randomised number to these attributes on a Magic Mob (made as a workaround to my last issue) but it has some weird functionality-
1) Upon initial cast it works as intended, giving each stat a random value 0-12
2) However, this randomised stat then re-rolls and randomises 0-12 again after any reloads and '/magic load'
3) The randomised stat is set back to 0 when the server restarts

Is there a way to ensure the randomised stat is saved/will stay the same after the spell is first used?

**Comment by PhvntxmX** [comment]
its just how rand function behaves, i think solution is just to store "ceil(rand(0,12)" into a ModifyVariable action's variables and use them for your ModifyEntity action

**Comment by NightScythe1** [comment]
> its just how rand function behaves, i think solution is just to store "ceil(rand(0,12)" into a ModifyVariable action's variables and use them for your ModifyEntity action

No luck with this unfortunately :( I tried adding the following to the start of the spell:
```
    - class: ModifyVariable
      variable: hprand
      value: ceil(rand(0,12))
```
and calling it back later via
```
        - class: ModifyEntity
          mage:
            attributes:
              health_dragon: hprand
```
(varying with 'hprand' and '@hprand' and '$hprand') but it doesn't seem to work at all, and the stat remains at 0

**Comment by PhvntxmX** [comment]
What about using command action and /mage command instead of this?

**Comment by PhvntxmX** [comment]
It doesn't fix the problem obviously, I but I'm sure it'll work as a temporary solution

**Comment by NightScythe1** [comment]
I'll give it a try now!

**Comment by PhvntxmX** [comment]
that's really strange, i need to test it myself...

**Comment by PhvntxmX** [comment]
This is working for me:
```test:
  actions:
    cast:
    - class: CustomProjectile
      actions:
        - class: ModifyProperties
          modify_target: "mage"
          modify:
          - property: attributes.ag
            value: rand(0,5)
        - class: Cast
          as_target: true
          spell: check
  parameters:
    target: other
    range: 32

check:
  actions:
    cast:
    - class: AreaOfEffect
      actions:
        - class: Message
          message_target: true
          message: "$ag -  dsadfasf"
  parameters:
    target: self
    target_self: false
    range: 5
    radius: 10
    y_radius: 10```

**Comment by PhvntxmX** [comment]
haven't tested that part, but i assume - yes

**Comment by PhvntxmX** [comment]
something here is definetly broken, these actions are not supposed to revert on restart - it's just breaks the whole purpose of them

**Comment by NathanWolf** [comment]
Have you tried ModifyAttributes instead of ModifyProperties?

Sorry if I'm not totally following, I'm honestly a little hazy on the difference between the two, especially when using the latter to modify attributes :|

**Comment by PhvntxmX** [comment]
> Have you tried ModifyAttributes instead of ModifyProperties?
> 
> Sorry if I'm not totally following, I'm honestly a little hazy on the difference between the two, especially when using the latter to modify attributes :|

Tried it now and it also does not work. I assume attributes itself are broken?

**Comment by PhvntxmX** [comment]
Also tried it on both magic and vanilla mobs - same result. So it's not a magic mob's template overwriting the data _i guess_

**Comment by NightScythe1** [comment]
> This is working for me:

I tried using this spell but it doesn't seem to work at all for me, it doesn't change the mob's stat and always prints '0'. The only things I changed from your original example was the attribute name-

```
test:
  actions:
    cast:
    - class: CustomProjectile
      actions:
        - class: ModifyProperties
          modify_target: "mage"
          modify:
          - property: attributes.health_dragon
            value: rand(0,5)
        - class: Cast
          as_target: true
          spell: check
  parameters:
    target: other
    range: 32

check:
  actions:
    cast:
    - class: AreaOfEffect
      actions:
        - class: Message
          message_target: true
          message: "$health_dragon"
  parameters:
    target: self
    target_self: false
    range: 5
    radius: 10
    y_radius: 10
```

**Comment by NightScythe1** [comment]
> 1. Upon initial cast it works as intended, giving each stat a random value 0-12
> 2. However, this randomised stat then re-rolls and randomises 0-12 again after any reloads and '/magic load'
> 3. The randomised stat is set back to 0 when the server restarts
> 
> Is there a way to ensure the randomised stat is saved/will stay the same after the spell is first used?

This also occurs if using SpawnEntity instead. Still struggling to find a way to allow Magic Mobs to keep set-stats after restarts & to allow placeholders for some of these equations.

```
    - class: SpawnEntity
      type: monstrous_nightmare
      mage:
        attributes:
          speed_dragon: ceil(rand(0,12))
```
