### ISSUE TITLE
Improved requirements format

### ISSUE THREAD

**Issue by temoya1** [elBukkit/MagicPlugin#1219]
The current "requirements" is very difficult to understand, so I think it would be better to use a form like "effects".
Like this

```yaml
reqs:
  - req: number
    number: attributeA
    more: 3
    less: 5
  - group: or
      - req: number
        number: variableA + attributeB
        value: 15
      - req: number
        number: variableB
        min: 5
  - group: and
      - req: wand
        target: source
        invert: true
        wands:
          - wand
      - req: light
        max: 5
        min: 3
```
```java
if (
  (attributeA > 3 && attributeA < 5)
  && ((varA + attributeB == 15) || (varB >= 5))
  && (!wands.contains(wand) && (light <= 5 && light >= 3))
) {
}
```
