### ISSUE TITLE
Suggestion- "mob_properties" parameter

### ISSUE THREAD

**Issue by NightScythe1** [elBukkit/MagicPlugin#1228]
Following on from recent bugs such as #1217, a potential suggestion I had is to add a system/parameter of 'mob_properties' that can be added to a mob's config that will be applied/generated when the mob is spawned, but not re-checked/overwritten on reloads and restarts and can be freely edited by spells afterwards. This is already possible on wands with 'item_properties'-

```
testwand:
  name: "testwand"
  item_properties:
    item_attributes:
      generic_attack_damage: (ceil(rand(15,30))/10)
      generic_attack_speed: -1.2
```
Which got me wondering if a similar alternative would be feasible for mobs too?
