### ISSUE TITLE
Weird reflection

### ISSUE THREAD

**Issue by Clexus** [elBukkit/MagicPlugin#1254]
Weird reflection of projectile when aim at a block
Will also reflect when hit an entity
I have set ignore_block to true
Is there any reflection settings
![image2](https://github.com/elBukkit/MagicPlugin/assets/62130504/60a8812e-e4a6-4e3a-b40e-04fb71e461d3)
![image](https://github.com/elBukkit/MagicPlugin/assets/62130504/ab3c34ee-aa62-4599-8f91-ed211c5d1c7f)
![Uploading IMG_9211.jpg…]()
?
![image](https://github.com/elBukkit/MagicPlugin/assets/62130504/5799457d-8895-4010-8176-990c16564edd)

**Comment by NathanWolf** [comment]
Spells can be configured to reflect off of things. What spell is this?

**Comment by Clexus** [comment]
> Spells can be configured to reflect off of things. What spell is this?

the spell created by me, no reflect option

**Comment by Clexus** [comment]
```
lasergunpro3:
  actions:
    cast:
    - class: CheckEntity
      allowed_entities: player
      actions:
      - class: Command
        op: true
        command: freeze @t 20
    - class: CustomProjectile
      hitbox_size: 0.5
      speed: 50
      ignore_blocks: true
      entity_hit_count: 8
      actions:
      - class: Velocity
        push: 0.03
      - class: Damage
        damage: 300
        magic_damage: false
        no_damage_ticks: 0
      - class: Damage
        damage: 20
        damage_type: OUT_OF_WORLD
        no_damage_ticks: 0
  effects:
    cast:
    - location: origin
      sound: laser.shoot2
      sound_volume: 2
    tick:
    - location: target
      effectlib:
        class: Trace
        particle: dragon_breath
        duration: 600
        iterations: 1
  headshot_parameters:
    damage_multiplier: 1.5
  parameters:
    target: other
```
