### ISSUE TITLE
Persistent Particle Effects Causing Performance Issues After Using Fling Magic

### ISSUE THREAD

**Issue by Wind0220** [elBukkit/MagicPlugin#1258]
After using the "Fling" magic, particle effects continue to generate upon landing until a jump is performed, causing an accumulation of particle effects that leads to lag and performance issues.

https://github.com/elBukkit/MagicPlugin/assets/96609471/0798aebe-3f99-43e6-895f-3f80dce64681

**Comment by NathanWolf** [comment]
It sounds like your server and/or players are having a lot of issues with particle performance.

Your players can turn off spell particles in the enchantment table menu if it’s a problem for them.

It is generally dependent on the players’ computers, particles are almost entirely clientside - but if you think it is a problem server-wide there is a command to turn them off globally. I don’t know it offhand, but something like `/mhelp disable particles` might have it.

**Comment by NathanWolf** [comment]
You *can* also edit individual spells to tweak particle counts down. This is a good bit more complicated, but `meditor spell fling` for instance will get you started with that. Just replace `fling` with `singularity` to edit that spell instead.

**Comment by Wind0220** [comment]
I apologize if I didn't explain clearly. The issue is that after using the "fling" magic, the particle effects generated upon landing persist and do not disappear. These effects continue until the player performs a jump. This behavior is causing inconvenience as players are required to jump to remove the effects manually. Thank you for your understanding.

**Comment by NathanWolf** [comment]
Oh, I see. That is strange, I will see if I can reproduce- the landing rings should only stay for a second or so.

Have you checked your server logs to see if there are any errors happening when players use that spell?

**Comment by Wind0220** [comment]
I have checked and there are no abnormalities or errors in the spell😟

**Comment by NathanWolf** [comment]
What version of the plugin are you on? `/magic` will tell you
Have you customized this spell at all?
I just tried it out on the latest dev build (10.8.10-snapshot) and I don't see this happening.

These effects are controlled by the `land` portion of the config, which looks like this (`/meditor spell fling`)

```
        land:
        -  sound: block_stone_step
           sound_pitch: 0.7
        -  class: EffectRing
           particle: block_crack
           source_location: feet
           period: 4
           particle_count: 80
           radius: 4
           particle_offset_x: 0.9
           particle_offset_z: 0.9
           particle_offset_y: 0.1
```

The definition does look a little weird, I am going to add `iterations: 4` to it, which should be the default ... that means it should repeat only 4 times, every 4 ticks (`period: 4`) so lasting 16 ticks is just under a second.
