### ISSUE TITLE
Server Latency Spikes for Some Players After Usage of Singularity Magic

### ISSUE THREAD

**Issue by Wind0220** [elBukkit/MagicPlugin#1259]
Following the activation of the "Singularity" magic by certain players, a notable increase in server latency has been observed, adversely affecting the gameplay experience for a portion of users. Despite our server's broadband speed of 20 Mbps, it appears that the usage of this magic is triggering substantial latency spikes for players. 
Before use
![b1897547cb79db1cc21fada80ce1116a](https://github.com/elBukkit/MagicPlugin/assets/96609471/9afb04f4-15d9-4efe-9600-00e9c886f1bf)
After use
![9489f78fdc351e859ab42c06e7064532](https://github.com/elBukkit/MagicPlugin/assets/96609471/01e9aff5-c44c-43cc-a899-33e4d3fd4211)
![fc3075a6bc4cfab8a01fed117f207636](https://github.com/elBukkit/MagicPlugin/assets/96609471/01e0502c-1675-4e03-ace4-352468a59be5)
![39a16af9f954bbbb26c56f23c739175a](https://github.com/elBukkit/MagicPlugin/assets/96609471/f79b8080-10b5-470b-95bc-69f06baf10b6)

**Comment by NathanWolf** [comment]
Use `/mconfig disable spell singularity` to turn that spell off.

**Comment by Wind0220** [comment]
I used the `/meditor spell singularity` command to reduce the particle effects after which the lag issue was resolved. Thank you very much!🎉

**Comment by NathanWolf** [comment]
If you care to share how you changed it I could update the defaults in case others are having this issue. If not, that's ok too :)

**Comment by Wind0220** [comment]
Actually, I didn't make significant changes...I simply reduced the particle effects by a lot. I believe the issue occurred previously due to excessive particles causing bandwidth utilization problems on the server. If you're truly interested, I can share the details with you, although it might not be very impressive. Your understanding is greatly appreciated.
```
singularity:
  # This has been added automatically so that anything you remove here does not get inherited back in from the default configs
  inherit: false
  icon: singularity
  category: master
  pvp_restricted: true
  worth: 1000
  earns: 15
  upgrade_required_path: student
  upgrade_required_casts: 50
  actions:
    cast:
    - class: Sphere
      actions:
      - class: ModifyBlock
        direction: 0,1,0
    - class: AreaOfEffect
      actions:
      - class: Velocity
    - class: Interval
      interval: 200
      actions:
      - class: AreaOfEffect
        actions:
        - class: Velocity
          speed: 0.25
          item_speed: 0.25
          entity_speed: 0.25
    - class: AreaOfEffect
      actions:
      - class: Velocity
        push: 3
      - class: Damage
  effects:
    cast_finish:
    - sound: entity_iron_golem_death
      sound_pitch: 0.3
      sound_volume: 0.2
    - sound: block_conduit_deactivate
      sound_pitch: 0.7
      sound_volume: 0.5
      effectlib:
        class: Modified
        iterations: 3
        duration: 150
        parameters:
          radius: 1.5 + (t/i) * 5
        effect:
          class: Sphere
          particle: redstone
          color: '#000000'
          particle_size: 0.6
          radius: 0.6
          # The original value is 150
          particles: 18
    cast:
    - sound: entity_wither_shoot
      sound_pitch: 0.4
    - class: EffectSingle
      sound: magic.bonk
      sound_pitch: 0.2
      sound_volume: 0.3
      location: origin
    - sound: block_conduit_deactivate
      sound_pitch: 0.7
      sound_volume: 0.5
    - sound: entity_bee_loop
      sound_pitch: 2
      location: target
    - sound: entity_wither_death
      sound_pitch: 0.5
      location: target
      target_location: block_center
      effectlib:
        class: Sphere
        duration: $duration
        particle: redstone
        color: '#000000'
        particle_size: 1.5
        radius: 1.5
        # The original value is 250
        particles: 31
    - class: EffectSingle
      location: target
      target_location: block_center
      effectlib:
        class: Modified
        duration: $duration
        period: 3
        parameters:
          radius: 8(1-(t/i))
          rotation: t/10
        effect:
          class: Helix
          particle: redstone
          color: '#000000'
          particle_size: 0.6
          # The original value is 70
          particles: 15
          curve: -2
  parameters:
    target_type: Entity
    range: 12
    target: block
    allow_max_range: true
    undo: 15000
    duration: 7000
    damage: 3
    speed: 0.75
    item_speed: 0.75
    entity_speed: 0.75
    brush: air
    player_damage: 10
    entity_damage: 15
    target_self_timeout: 2000
    target_self: true
    push: -1
    falling: true
    radius: 4
    y_radius: 4
    cooldown: 30000
  costs:
    mana: 50

singularity|2:
  parameters:
    radius: 6
    y_radius: 6
    player_damage: 15
    entity_damage: 20
    duration: 10000
```
