### ISSUE TITLE
create a way to delete original block's drop

### ISSUE THREAD

**Issue by rhisth** [elBukkit/MagicPlugin#1269]
how to select the item with areaofeffect class that falls out of the block when you break it?
i tried to select items that i drop with dropitem class and everything works, but not with the item that falls out of the block

(executes a spell to drop the item)
```
fantasy:
 world: world
 block_break:
  iron_ore:
   class: Cast
   types: iron_ore
   spells:
    piece_iron
```

here i am trying to select iron ore that falls out of the block, but it doesn't select it.
and then dropping my custom items that are actually wands (works)
```
piece_iron:
 name: ironblock
 icon: stick
 actions:
   cast:
   - class: AreaOfEffect
     radius: 1
     actions:
       - class: RemoveEntity
         target_types: dropped_item,experience_orb
   - class: Repeat
     repeat: rand(1, 3)
     target: self
     actions:
     - class: DropItem
       item: piece_iron
```

if i add this my items are getting selected and removed, but not iron ore that falls out of the block
```
   - class: AreaOfEffect
     radius: 1
     actions:
       - class: RemoveEntity
         target_types: dropped_item,experience_orb
```

whats the problem?
