### ISSUE TITLE
ModifyBlock does not undo when WitherSkull explodes

### ISSUE THREAD

**Issue by tororo1066** [elBukkit/MagicPlugin#1314]
I'm trying to create a spell that produces a barrier that disappears after 2 seconds.
This usually works,
```yaml
barrier2:
  # This has been added automatically so that anything you remove here does not get inherited back in from the default configs
  inherit: false
  icon: walls
  costs:
    mana: 5
  actions:
    cast:
    - class: Equation
      x_equation: 0
      y_equation: 1
      z_equation: 0
      variable: t
      iterations: 2
      actions:
      - class: ModifyBlock
      - class: PlayEffects
        effects: column
      - class: Skip
        skip: 4
        actions:
        - class: Delay
          delay: 10
  parameters:
    target: other
    allow_max_range: true
    range: 7
    undo: 2000
    thickness: 1
    bypass_build: true
    transparent: transparent_to_construction
    brush: glass
    brushcolor: true
    breakable: 3
    unbreakable: true
    destructible: destructible_replace
    volume_type: xzy
    oty: 1
```
However, if WitherSkull projectile explodes near the barrier, it will not disappear.

https://github.com/elBukkit/MagicPlugin/assets/71592738/8ef08f70-3602-4d32-aa87-957b1f11c1b1
