### ISSUE TITLE
Shop.

### ISSUE THREAD

**Issue by Olivo123** [elBukkit/MagicPlugin#132]
Hello, I love your plugin but I can't find how to change the Price of the spells of the shop, can you tell me how to do it please? Thanks.

**Comment by WasdCat** [comment]
I've got the same problem :(

**Comment by thexplosionst** [comment]
Yes please help

**Comment by NathanWolf** [comment]
You have two options here:

1. Customize spells (use spells.yml) to change the "worth" value for each spell, like so
```
blink:
   worth: 1000
```

2. Create your own spell shop with a specific set of spells and prices.
```
myshop:
    icon: iron_hoe
    category: npc
    hidden: true
    actions:
        cast:
        -  class: SpellShop
    parameters:
        quiet: true
        confirm_filler: stained_glass:5
        spells:
          blink: 1000
          fling: 900
```
