### ISSUE TITLE
Attribute default & minimum mismatched effects?

### ISSUE THREAD

**Issue by NightScythe1** [elBukkit/MagicPlugin#1332]
After doing some more testing with attributes, I've noticed that the `min` and `default` configurations don't take the intended effects. Setting a value in the `default` field does correctly set it as the default, but it also overrides the `min` field. This means whatever value is set in `default` becomes the new `min`/minimum.
For example, a config that looks like this:
```
destruction:
  default: 100
  min: 0
  max: 200
```
Will *act* like a config that looks like this:
```
destruction:
  default: 100
  min: 100
  max: 200
```
