### ISSUE TITLE
Make variables usable in effects

### ISSUE THREAD

**Issue by Clexus** [elBukkit/MagicPlugin#1359]
title
```
effects:
    cast:
    - location: origin
      effectlib:
        class: Cylinder
        duration: 1000
        enable_rotation: true
        angular_velocity_x: 0
        angular_velocity_y: 0
        angular_velocity_z: 0
        rotation_x: pi/2
        rotation_y: yaw*pi/180
        height: 5
        radius: 0.3
        particle: flame
```
like this
