### ISSUE TITLE
"item_properties" doesn't take effect on wand upgrades

### ISSUE THREAD

**Issue by NightScythe1** [elBukkit/MagicPlugin#1389]
If an upgrade has an attribute defined in 'item_properties', it will not take any effect on the wand it is used on. Here's an example:

```
wand_name:
  upgrade: true
  item_properties:
    attributes:
      attribute_name: 1
```
^This upgrade *should* apply a +1 to the attribute on the wand it's placed on, but this doesn't actually happen.
However, attributes *will* apply on an upgrade if formatted like this:
```
wand_name:
  upgrade: true
  attributes:
    attribute_name: 1
```
The issue arises when trying to define randomised bonuses on these wands. A wand's randomised value for the attribute will re-randomise every time Magic reloads, *unless* it's placed in 'item_properties', in which case it only randomises once & is then saved. Since upgrades don't seem to apply anything under 'item_properties' to the wand they're slotted onto, upgrades can't have randomised values.
