### ISSUE TITLE
Target myself

### ISSUE THREAD

**Issue by vajuvung** [elBukkit/MagicPlugin#1429]
```
boss888888888:
  actions:
    cast:
    - class: CustomProjectile
      actions:
      - class: ChangeContext
        target_self: true
        actions:
        - class: Repeat
          repeat: 500
          actions:
          - class: AreaOfEffect
            actions:
            - class: Velocity
              push: -1
            - class: Delay
              delay: 100
  parameters:
    target: block
```
i want to target myself only, but when i hit block with spell, still target nearby entity. any solutions?
