### ISSUE TITLE
crafting.yml

### ISSUE THREAD

**Issue by namessos** [elBukkit/MagicPlugin#146]
Hello you beautiful person you. i am enjoying your plugin so far you gorgeous you. i have but one tiny problem, i would like to enable crafting that magical cube. i have no idea what to write in the crafting.yml, and all the links lead to error 404. could you please give me the code t write?

**Comment by NathanWolf** [comment]
Magical cube? :D 

Not sure what you mean but I can direct you to the crafting configs as examples:

https://github.com/elBukkit/MagicPlugin/tree/master/Magic/src/main/resources/defaults/crafting

**Comment by namessos** [comment]
yes! the cube that spawns buildings! the magic engineereing thingy?

**Comment by NathanWolf** [comment]
Oh, the Wolf House! Lol, so OP :D 

Fun fact.. I built that original house by hand in survival ;)

Ok- so that should be pretty easy, just put something like this in your crafting.yml

```
wolfhouse:
  enabled: false
  output: wolfhouse
  output_type: wand
  materials:
    o: nether_star
    i: emerald
    f: firework
  row_1:
  row_2: ioi
  row_3: ifi
```

**Comment by namessos** [comment]
sorry to bother, i put the materials and it's not working. firework? or firework rocket?

**Comment by NathanWolf** [comment]
I think it needs to be the actual rocket item- maybe not a great example though. You can change the materials to anything from here:

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

Maybe just use some sticks or something to test. This will require a full server restart too, not just a "/magic load"- crafting recipes have to be installed on startup.

**Comment by namessos** [comment]
so, i replaced firework with IRON_BLOCK, and still nothing. maybe you can take a quick peek at this and see what i did wrong?
http://imgur.com/a/eDKuV

**Comment by NathanWolf** [comment]
Hm that looks right to me- can you check your server logs, at startup it should print whether it successfully added the recipe or not.

So that should be like 2 emeralds (the item) on the left, then nether start on top of an iron block, then two more emeralds to the right?

Another option is to just try a much simpler recipe to start with.. maybe like this:

```
wolfhouse:
  enabled: true
  output: wolfhouse
  output_type: wand
  materials:
    o: emerald
  row_1:
  row_2: o
  row_3: o
```

If you can't get it working I can try it out myself, but it won't be right away.
