### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by shootcraft** [elBukkit/MagicPlugin#151]
How to increase projectile damage of the spells such as fire spells, I even try to add damge: 1000 but it wont work, but it will work for arrowrain

**Comment by NathanWolf** [comment]
The fire spell doesn't do direct damage, it just causes fire. There's no way (at least not in Magic) to make fire do different damage.

If you wanted to make a custom spell for that, you would combine the Fire action and the Damage action, so it does both.

**Comment by shootcraft** [comment]
there is no way to config those damage and fire action together using magic plugin ? if there is a way how can I config it and the documentary to create custom was removed, can you send me latest one or teach me to config it ? :)

**Comment by NathanWolf** [comment]
Documentation was not removed, but really you just have to learn by example. Check the wiki:

https://github.com/elBukkit/MagicPlugin/wiki/Customization

There's just too much there to have it all documented- the default spells _are_ the documentation.

In this case, you would look at the fire spell and modify it. Here's probably what you want- this would go in plugins/Magic/spells.yml :

```
fire:
    parameters:
        damage: 10
    actions:
        cast:
        - class: CustomProjectile
          actions:
          - class: AreaOfEffect
            actions:
            - class: Damage
          - class: Disc
            actions:
            - class: Cover
              actions:
              - class: Burn
```

I took the list of actions from the fire spell:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/defaults/spells/fire.yml

And I added an AreaOfEffect + Damage action set. This will damage any entities within a radius of where the spell hits. That radius will match the radius used in the "Disc + Cover + Burn" action set to cover a disc of blocks with fire.

I then added a "damage" parameter to control the damage done by the Damage action.
