### ISSUE TITLE
Recall problems

### ISSUE THREAD

**Issue by iKezzaUK** [elBukkit/MagicPlugin#162]
I have created multiple warps (commandbook warps) on my server, and when i try and cast "Recall" The particle effects happen, but no UI appears so i can select a warp :/

**Comment by NathanWolf** [comment]
Recall doesn't automatically know about your warps- you need to configure it by adding a "warps" parameter list. See here for an example:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/examples/elworld/spells.yml#L72

**Comment by iKezzaUK** [comment]
Ok, so do i replace:
warps:
      [warp from CommandBook]:
        name: [Own Name]
        description: [own description]
        server: [worldname]
        locked: true
        icon: compass

**Comment by NathanWolf** [comment]
That's right. More specifically, you'd add something like this to your spells.yml (or to spells/recall.yml [you have to create this file], whichever you prefer)

```
recall:
  parameters:
    warps:
      yourcommandbookwarp:
        name: Somewhere cool
        description: This will show in the tooltip
        icon: compass
```

If you put "locked: true" on a warp that means the player won't see it until it's unlocked. I normally use this with WGRegionCommands, having a region issue the command "/castp @p warpunlock unlock yourcommandbookwarp". In this way the players can collect Recall waypoints as they explore.
