### ISSUE TITLE
Common player files for 2 separate servers

### ISSUE THREAD

**Issue by Blamo27** [elBukkit/MagicPlugin#167]
Hello,

Is it possible to link the player files of Magic for 2 separate servers ? We want those files to be common to the 2 servers we have (both PVP and PVE). These are not mirror servers, but two different servers that requires Magic player files to be linked. Maybe you could add SQL backend...?

Thank you.

**Comment by NathanWolf** [comment]
Probably not anytime soon, though there is a framework in place for you to add your own data handler if you'd like to set it up yourself:

https://github.com/elBukkit/MagicPlugin/blob/master/MagicAPI/src/main/java/com/elmakers/mine/bukkit/api/data/MageDataStore.java

You can implement that interface, and then add your player data handler to your configs like this:

```
player_data_store:
  class: com.mystuff.magic.MagicDatastore
  # You can add parameters here that will get passed into your data store, if you want
  folder: data/players
```

Your other option is to use a NAS (or some other network file store that you can mount on each of your servers) and symlink the Magic/data folder on each server to the one central store.
