### ISSUE TITLE
Make players not cast in certain areas and wand core

### ISSUE THREAD

**Issue by Cornelwallace** [elBukkit/MagicPlugin#192]
Hi there! I was wondering if there was a way I could make players not cast certain spells in certain areas and the other thing I wanted is to make wands have cores which im having trouble trying to figure out.

**Comment by NathanWolf** [comment]
You can use the latest version of WorldGuard, Magic will add some flags. You can then do /region flag <region> blocked-spells accio,apparate,etc

There is no such thing as "cores", really. Wands have a description- you can have that description randomized. You should really just use the potter configs and customize from there :)

The relevant parts of the configs are here in messages.yml:

```
randomized:
   wood:
     - Acacia
     - Alder
     - Apple
     - Ash
     - Aspen
     - Beech
     - Blackthorn
     - Black Walnut
     - Cedar
     - Cherry
     - Chestnut
     - Cypress
     - Dogwood
     - Ebony
     - English Oak
     - Elder
     - Elm
     - Fir
     - Hawthorn
     - Hazel
     - Holly
     - Hornbeam
     - Larch
     - Laurel
     - Mahogany
     - Maple
     - Oak
     - Olive
     - Pear
     - Pine
     - Poplar
     - Red Oak
     - Redwood
     - Rosewood
     - Rowan
     - Silver Lime
     - Spruce
     - Sycamore
     - Vine
     - Walnut
     - Willow
     - Yew
   core:
     - Unicorn Tail Hair
     - Dragon Heartstring
     - Pheonix Feather

wands:

    default:
        name: Wand
        description: $wood and $core

    wandbox:
        name: Wand
        description: $wood and $core
```
