### ISSUE TITLE
Alohomora on iron doors - General questions .

### ISSUE THREAD

**Issue by Ahrigumi** [elBukkit/MagicPlugin#241]
hello again nathan :) 

I have a dude respect "Alohomora" , I tried to open iron doors with "Alohomora" but nothing happends, what can I do? or I do something bad?

**Comment by NathanWolf** [comment]
No it's intentional that it doesn't work on iron doors- if you want to change that, add this to spells.yml

'''
alohomora:
  parameters:
      destructible: doors
'''

I should probably make it level up like its survival counterpart, which opens iron doors at level 2.

**Comment by NathanWolf** [comment]
Hm sorry on my phone looks like I botched the indentation there - make sure each line is indented farther than the last, I'll try and fix the comment when I can :)

**Comment by Ahrigumi** [comment]
oh! i will test, 2 question... how can i implement spells of others mode with the main potter? , something like this?

 add_examples:
   - potter
   - beding

and.. how can i translate the tipe of wind? for example... 
![sin titulo](https://user-images.githubusercontent.com/29241452/27012127-7cf82cd4-4eca-11e7-95ee-734faef108ca.jpg)

I dont find it in "messages.yml"

**Comment by NathanWolf** [comment]
Should look like this in config.yml:

```
add_examples:
- potter
- bending
```

Wandlore is in the potter configs, messages.yml, under "randomized":

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/examples/potter/messages.yml#L569

**Comment by Ahrigumi** [comment]
Nice! I have all except one more thing , the message when you buy a wand by the ticket, I'll try to translate:

    ollivander:
        cast: You exchanged $requires for $item
        insufficient_resources: You must have $requires
        title: "Ollivander" 

but doesnt work :/

**Comment by Ahrigumi** [comment]
Hello! amm.. how can i modify the inherit of spells? I want to replace incencio from potter for fire from bending

**Comment by NathanWolf** [comment]
Make sure that's in the "spells" section of messages.yml, should work.

**Comment by Ahrigumi** [comment]
I tryed again and ...
![sin titulo](https://user-images.githubusercontent.com/29241452/27045872-aa047880-4fa2-11e7-9144-abd2ac604c9e.png)

**Comment by Ahrigumi** [comment]
Ok, i fix it , I put "insufficient:" on ollivander and works so nice :)
   
    ollivander:
        cast: You exchanged $requires for $item
        insufficient_resources: You must have $requires
        title: "Ollivander"
        insufficient: You dont have a ticket

**Comment by Ahrigumi** [comment]
Also, I tryed to put a new resourcepack (with the default of magic) in "config.yml" and I have this message 
![sin titulo](https://user-images.githubusercontent.com/29241452/27052401-ddb6aac4-4fb9-11e7-99b1-e543db93df8b.png)
What can I do?

**Comment by Ahrigumi** [comment]
Fix it :P

**Comment by NathanWolf** [comment]
You can add a "deducted" string in there to change the "You bought" text.
```
ollivander:
  deducted: "..."
```

**Comment by Ahrigumi** [comment]
Nice! its works! , I tell you , I want to disabled the crafting of brooms with "enable_crafting: false" in config.yml , why? Because I want to sell them. So, how can I get the brooms? and , can I put  them in a normal plugin shop?

**Comment by NathanWolf** [comment]
You can use a magic NPC with "broomshop" if you want.

Few shop plugins can handle magic items. Shopkeepers can, perhaps any plugin which lets you add items in-game will work (not dtlTraders). Essentials sign shops can do it due to Magic integration (use wand:broomstick on a sign... if it fits). But any shops that use config files are not likely to have a way to add items with custom data.

/mgive broomstick

Will give you one, if you want to test adding it to your own shops. I recommend using Magic's shops though.

/npc Brooms
/trait magic
/mtrait broomshop

**Comment by Ahrigumi** [comment]
oh! I didn't know that , so.. I will use the Magic's shop of course :P , Is the same with the upgrade of wands?

**Comment by NathanWolf** [comment]
You can put "spellshop" on an NPC for that, buying spells is the normal way for wands to get upgraded.

You can make a shop that sells mana upgrades and such too but I've got nothing built in for that.

**Comment by Ahrigumi** [comment]
If it's not too much trouble, can I ask how to do it?

**Comment by Ahrigumi** [comment]
I tryed to find my error but I cant solve this.

I tryed to create a brooms shop or "/mgive broomstick" but i have the same message " "Spell broomshop unknown""

**Comment by NathanWolf** [comment]
Oh, I forgot, potter configs :D 

Try adding this broomshop to spells.yml:

```
broomshop:
    icon: gold_spade
    category: npc
    hidden: true
    actions:
        cast:
        -  class: ItemShop
    parameters:
        quiet: true
        confirm: true
        confirm_filler: stained_glass:3
        items:
        - item: wand|firebolt
          cost: 10000
        - item: wand|nimbus
          cost: 5000
        - item: wand|comet290
          cost: 1000
        - item: wand|cleansweep1
          cost: 500
        - item: wand|bluebottle
          cost: 100
```

And refer to the wands in there for "/mgive" - potter configs have several different brooms.

**Comment by Ahrigumi** [comment]
Nice ! Works perfectly , and... how can traslate the messages? , "costs 100 emerals" and "You bought 1 ..." , I tryed for the last "deducted" in "spells/brooms" in "messages.yml" but dont works .
And... how can I change the appearance of wands? I tryed to find the textures but is confuse to me. I can see a lot of wands , i want to modify wands of "example: potter"

**Comment by NathanWolf** [comment]
Here is the spellshop example which has most of the text customized:

```
spells:
    spellshop:
        name: Spell Shop
        title: "$path Spells ($balance)"
        description: Buy spells for your current level
        cost_lore: "Costs: $cost"
        no_items: There are no spells for you to buy here
        no_path: You may not learn with that $wand.
        no_upgrade: There is nothing more for you here.
        no_required_path: You must be at least $path!
        no_path_end: You must be ready to advance from $path!
        no_wand: You must be holding a wand!
        insufficient: "&4Costs &c$cost"
        confirm_title: "Buy $item"
        deducted: "&d&oYou bought &r&6$item &r&d&ofor &r&a$cost"
        fail: ""
```

That would go in messages.yml, under the name of your shop spell. Each shop can have its own different text, unfortunately this means you need to translate each one. I'll try and think of a better way to handle that.

To change textures, you unzip the RP, replace textures, then zip it back up. This is easy for potter wands because they are just textures and not 3D models. The potter wand textures are here:

https://github.com/elBukkit/MagicPlugin/tree/master/Magic/src/resource-pack/default/assets/minecraft/textures/items/flat

So just replace the png files in the "flat" folder.

**Comment by Ahrigumi** [comment]
Oh! Ok, thank you so much, in the RP folder i can see a variety of wands, the wand by default (potter)  is the "black" , can choose other wands like "skinny" or "wolf" if i rename the "black" wand ? or can I create "ollivanders" and buy 4 types of wands? (black, skinny, wolf ,brown and elder)

**Comment by NathanWolf** [comment]
Black, skinny and brown are the 3 used by default. Ollivander will give you a wand box, when you open the box it contains a random one of those 3. (The wand chooses you....)

If you want to make a shop instead and let players choose, you could do that but it would take a bit of work.

Another option is to make a separate shop where they can spend money to change the appearance of their wand.

The wolf wand is for me, you could replace the texture and give it out as a 4th wand appearance, the texture as-is is not very Harry Potter-ish. The elder wand is of course the icon for the elder wand, if I were you I'd leave that in as a special admin wand but that's up to you.

You can also add more texture, as many as you want, this is just a little more complicated.

**Comment by Ahrigumi** [comment]
Dammit is true . The wand chooses me jajajaja , so... if I want the wolf wand Is difficult because the wand box is random... and how can I create a shop to select the appearance of wand? It's just curiosity

**Comment by NathanWolf** [comment]
Ha

You can make a shop like this:
```
appearanceshop:
    icon: wood_hoe
    inherit: buyshop
    parameters:
        auto_close: true
        confirm: true
        confirm_filler: stained_glass:3
        require_wand: true
        items:
        - item: wand|skinny_upgrade
          cost: 1000
        - item: wand|brown_upgrade
          cost: 1000
        - item: wand|black_upgrade
          cost: 1000
```

If you want more appearances, you have to add the upgrade items to your wands.yml. They are pretty simple, look like this:

```
black_upgrade:
    name: Black Wand Appearance
    upgrade: true
    icon: wood_hoe:25
    upgrade_icon: wood_hoe:25
```
