### ISSUE TITLE
Particles stopped working in 1.12?

### ISSUE THREAD

**Issue by mibby** [elBukkit/MagicPlugin#245]
Magic dev 2162
Paper dev 1122 (Spigot 1.12)

When I look up and right click to equip the hat item, no particles show up. Did they break in 1.12 or am I missing something?

Spells.yml
```
magichat:
    icon: diamond_axe:138
    icon_disabled: diamond_hoe:138
    hidden: true
    icon_url: http://textures.minecraft.net/texture/2abee4fe341011b9a0ae2fb83644f695521fd4e4c6198fe23112f1acbf38369
    category: utility
    worth: 100
    actions:
      # Aim up and cast, and the hat goes on your head
      alternate_up:
      - class: Delay
        delay: 1
      - class: Hat
    effects:
      cast:
      -  class: EffectSingle
         location: target
         effectlib:
           class: SphereEffect
           iterations: 4
           particle: smoke_large
    parameters:
      target_self: true
      use_item: true
      reason: custom
```

Wand.yml
```
hat_book:
    name: Book Hat
    mode: cast
    active_spell: magichat
    icon: diamond_spade:1
    indestructible: true
    locked: true
    keep: true
    effect_color: '888888'
    spells:
        - magichat
```

**Comment by mibby** [comment]
I also noticed that 
```
    locked: true
    keep: true
```
do not specify on the item that it is limited to that person only. Did that break too?

**Comment by NathanWolf** [comment]
Particles appear working to me. Are you looking in 3rd person? There's a cloud of smoke.

bound: true is what makes items bound to a player.

locked means it can't be modified, keep means it's kept on death.

**Comment by mibby** [comment]
> Are you looking in 3rd person? There's a cloud of smoke.

I am. I can record something in a bit to show you. 

> bound: true is what makes items bound to a player.

Thanks, I'll try that. Wiki page still needs to be finished. :)
https://github.com/elBukkit/MagicPlugin/wiki/WandParameters

**Comment by NathanWolf** [comment]
Seems pretty odd that particles for just that one spell would be broken - others are working?

Feel free to update the wiki if you want to lend a hand! ;)

**Comment by mibby** [comment]
@NathanWolf Sorry for the delay. Here is a video clip showing that particles do not display when equipping a magic hat. At the end of the video, I show that particles function on the server and are enabled / visible on the client. 

https://www.dropbox.com/s/0pjj0vxw6xvb9lc/2017-06-22%2002-55-47.mkv?dl=0

Am I missing something obvious?

(Wand) Hat.yml
```
hat_tophat:
    name: TopHat Hat
    mode: cast
    active_spell: magichat
    icon: diamond_spade:7
    indestructible: true
    locked: true
    keep: true
    bound: true
    effect_color: '888888'
    spells:
        - magichat
```

Spells.yml
```
magichat:
    icon: diamond_axe:138
    icon_disabled: diamond_hoe:138
    hidden: true
    icon_url: http://textures.minecraft.net/texture/2abee4fe341011b9a0ae2fb83644f695521fd4e4c6198fe23112f1acbf38369
    category: utility
    worth: 100
    actions:
      # Aim up and cast, and the hat goes on your head
      alternate_up:
      - class: Delay
        delay: 1
      - class: Hat
    effects:
      cast:
      -  class: EffectSingle
         location: target
         effectlib:
           class: SphereEffect
           iterations: 4
           particle: smoke_large
    parameters:
      target_self: true
      use_item: true
      reason: custom
```
