### ISSUE TITLE
Permissions "Magic.commands.*" and "Magic.create.*" do not work!

### ISSUE THREAD

**Issue by k-jiang** [elBukkit/MagicPlugin#255]
Platform: Spigot 1.12 build 1171
Magic 6.9.11
zPermissions 1.4 https://www.spigotmc.org/resources/zpermissions.11736/updates

FYI: those two permissions are not found in plugins.yml. In fact I could not found any of permission that comes with a wildcard "*". I have no choice but to manually add every single permission by hand.

Please fix it. Thank you so much.

**Comment by NathanWolf** [comment]
Wildcards are generally handled by the permissions system. If zPermissions doesn't support them, you should consider getting a better permission plugin. PEx works great. GroupManager as well.

I'll leave this open for now but I don't really plan on added specific support in Magic for wildcards since most permission plugins handle it fine on their own.

**Comment by k-jiang** [comment]
There are reason for ppl to choice a different permission system. For me zPermissions because it is the only permission that provide a per-world, per-region, bug-free, well-organized MySQL support (AKA the almost perfect permission), unlike PEx which has intention to put every chaos in a single SQL table. It makes life so much easier, especially when you trying to develop some custom api that suit your website / multi-server needs.
Beside, switching permission is never an easy task. We have thousands of permissions node set in 5 servers. I don't want to make things complected.

So how to fix it? This is what a section of [EssentialsX's plugin.yml](https://github.com/drtshock/Essentials/blob/203d6561acc04ef7193292d3d35b0a3a8b4b205f/Essentials/src/plugin.yml#L511), "the (step)Father of GroupManager" looks like:
```
permissions:
  essentials.*:
    default: op
    description: Give players with op everything by default
    children:
      essentials.gamemode.*: true
  # These permissions can't be assigned from player-commands for compatibility reasons
  essentials.teleport.cooldown.bypass.tpa:
    default: true
    description: If the player does not have this permission, /tpa will have cooldown even with the parent bypass perm
```
See it is not that hard to fix it.
