### ISSUE TITLE
Exploit - Wands are not bound when given from console and it goes into a slot currently not equipped.

### ISSUE THREAD

**Issue by mibby** [elBukkit/MagicPlugin#270]
Magic v6.9.18

@NathanWolf Found a little issue with ```bound: true```.

All of my wands are set to be bound to the player to avoid them from being duped in creative. I provide wands to players from a shop that runs the command ```/mgive <player> <wand> 1``` from console. Usually the wand is bound to the player upon receiving but if they are currently holding something in their inventory, the wand goes into another slot and does not get the bound attachment - allowing people to give away, sell, or even dupe the item.

```
pumpkin:
    name: Pumpkin
    mode: cast
    active_spell: magichat
    icon: diamond_spade:2
    indestructible: true
    locked: true
    keep: true
    bound: true
    effect_color: '888888'
    spells:
        - magichat
```
