### ISSUE TITLE
Add FallProtection support for actions on landing

### ISSUE THREAD

**Issue by 4kz** [elBukkit/MagicPlugin#303]
Hello,
I know you are busy so *PLEASE* reply only when you have time.

I think I've "fixed" the "smash" spell that was under "testing" somewhere in the examples folder in this repo.
but I think that it would be 1000 times better if there was a way for the sphere action to happen only when the player actually "lands" on the ground, after the velocity action. I would like to ask is if there's a way to do that because right now all that I'm doing is wait for one second and then have the "sphere" happen.

here's the spell

```
 SmasherStrike:
     actions:
         cast:
         - class: FallProtection
         - class: Velocity
           direction: 0,1,0
         - class: Delay
         - class: Velocity
         - class: Delay
           delay: 1000
         - class: ChangeContext
           target_caster: true
           actions:
           - class: Sphere
             actions:
             - class: BreakBlock
     parameters:
         duration: 1
         target: self
         min_speed: 5
         max_speed: 5
         delay: 500
         falling: true
         speed: 0.9
         brush: air
         radius: 5
         undo: 15000
         destructible: solid
         destructible_override: true
         destructible_durability: 45
         break_durability: 20
```
