### ISSUE TITLE
[MobArena] - Block Destruction

### ISSUE THREAD

**Issue by CollinHerber** [elBukkit/MagicPlugin#324]
#Category: Bug/Feature Request

##Expected Behavior
Blocks don't break when the arena is protected.

##Actual Behavior
Spells that destroy blocks are also destroying the MobArena protected blocks.

Magic Version: 7.0.1
MobArena Version: 0.99

**Comment by NathanWolf** [comment]
Hm, personally I disagree. I like my arenas destructible (via spells, but not permanently via players breaking things).

Can you just put a WG region around it?

If not I can looking into adding an option for this, assuming MobArena has some API I can use to tell if a block is inside of an arena.

**Comment by CollinHerber** [comment]
WorldGuard regions around the arena can be a bit screwy, they have posed to be troublesome for killing particular mobs. We found the best way to keep the MobArena behaving how it wants, was by having no regions assigned to the Arena and having the MobArena plugin handle everything on it's own.

I agree that SOME MobArena's could be destructible, and could pose to be fun but the option for people like myself that don't want the Arena to be destructible is a good addition.

It would be wise to account for multiple arenas on a single server, some of them are destructible, and some are not. Allowing the the configuration of all arena's would be pretty neat.

//Within the Config.yml for MagicPlugin
Example:
//MobArena Configuration
//Example: 
// arenaName
//     protected-from-magic: true/false/yes/no

**Comment by NathanWolf** [comment]
That WorldGuard behavior sounds weird, but fair enough!

I added what you requested in 7.1.3, just released on spigotmc. Or grab latest dev build.
```
# MobArena integration
mobarena:
  # Use this to disable all MobArena integration
  enabled: true
  # Set this to true for magic build/break permissions to respect protected arenas
  protect: false
  # This can be used to protect specific arenas by name
  # protected:
  # - arena1
  # - arena2
```
