### ISSUE TITLE
Wand buffs error

### ISSUE THREAD

**Issue by TofPlays** [elBukkit/MagicPlugin#376]
The wand buffs don't work:
![image](https://user-images.githubusercontent.com/33004077/39729659-edf60e4c-5211-11e8-90a1-0dacf2ff61ee.png)

**Comment by TofPlays** [comment]
![image](https://user-images.githubusercontent.com/33004077/39729869-052f707a-5213-11e8-9116-8431dcaa3f72.png)
![image](https://user-images.githubusercontent.com/33004077/39729886-1432d54e-5213-11e8-81f1-275ed8ff0888.png)
![image](https://user-images.githubusercontent.com/33004077/39729897-1ebb9db6-5213-11e8-9217-a4562062769d.png)

**Comment by TofPlays** [comment]
I added them in the wand's yml file and it used to work in the previous versions, only after the update they stopped working. Also Using the buffs shop spell where you add those buffs to a wand, they do the same thing

**Comment by NathanWolf** [comment]
Oh, ok thanks I bet I know what's up- they are working, but unfortunately they were changed in a way that break custom localizations.

If you have a `wand.protection` entry in your messages.yml, you will need to remove it. If you've customized all of the protection lore you'll need to re-arrange it a bit- the new config looks like this:

```

    protection:
      overall: "&2Protection $roman"
      physical: "&2Physical Protection $roman"
      projectile: "&2Projectile Protection $roman"
      fall: "&2Fall Protection $roman"
      fire: "&2Fire Protection $roman"
      explosion: "&2Blast Protection $roman"
      magic: "&2Magical Protection $roman"
      unknown: "&2$type Protection $roman"
```

This was done to support custom protections with custom damage types. I'll bet you have something like `protection: "&2Protection $roman"` in there, which is breaking things because it expects a whole section now instead of a single string.

A regrettable change in retrospect, but that's progress I guess.
