### ISSUE TITLE
Mount and unmount brooms with API

### ISSUE THREAD

**Issue by christophe6** [elBukkit/MagicPlugin#385]
Hi

Is there a way with the magic api to let a player mount a broom that's not in their inventory? After unmounting they should not get the broom.

Any ideas? Thank you!

**Comment by NathanWolf** [comment]
Yes, basically make a new broom spell like

```
instabroom:
  parameters:
    mount_wand: false
    helmet_item: wood_hoe:11
```

Then cast that via the API.
