### ISSUE TITLE
Breaking Modified blocks doesn't regenerate them

### ISSUE THREAD

**Issue by martdamp** [elBukkit/MagicPlugin#386]
Hey Nathan,

If you break a block that has been modified, then when you break one of those blocks it doesn't regenerate the block. I created a spell to test this and I have a 100% succes rate at recreating this bug. Just cast the spell, break some of the blocks and wait till the spell undos.

Greetings, martdamp

```
earth_test:
    icon: stone
    actions:
        cast:
        -   class: ChangeContext
            target_offset: 0,1,0
            actions:
            -   class: Disc
                radius: 5
                actions:
                -   class: Cover
                    actions:
                    -   class: ModifyBlock
            -   class: Delay
                delay: 500
            -   class: Disc
                radius: 5
                actions:
                -   class: Brush
                    brush: erase
                    actions:
                    -   class: ModifyBlock
                        speed: 0.4
                        direction: 0,1,0
    parameters:
        target: block
        y_size: 1
        brush: sand
        undo: 10000
        falling: true
```
