### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by shootcraft** [elBukkit/MagicPlugin#391]
Hi , Nathanwolf 

May I know how to setup a wand where the inventory selector will remain at a spells after selecting the spells  without the selector jump back to  the wand ?

**Comment by NathanWolf** [comment]
It's not possible, the wand has to be the selected item for it to work.

Try this config in wands.yml:
```
wand:
  mode: skills
  skills:
    quick_cast: false
```
That will make a wand like a spellbook. You take the spells out and right-click them to use them. That's about as close as you can get.
