### ISSUE TITLE
Wands are deactivated when an active_icon is used

### ISSUE THREAD

**Issue by killme** [elBukkit/MagicPlugin#394]
When using a wand with an `icon_active` as follows:
```
a:
    upgrade: true
    icon: diamond_sword:1189
    icon_inactive: diamond_sword:1188
```

The wand is deactivated upon glide toggling by the wand tick, which checks if the item instance is still the same.
