### ISSUE TITLE
Path progress, upgrade_item dosen't fully work

### ISSUE THREAD

**Issue by Testerro** [elBukkit/MagicPlugin#441]
I customized paths and my progression looks like this: `Rycerz -> Paladyn`
```
utility:
    inherit: default
    extra_spells:
      - push
(...) much more spells

rycerz:
    inherit: utility
    name: Rycerz
    upgrade: paladyn
    upgrade_item: paladyn_upgrade
    spells:
      - dash
(...) much more spells

paladyn:
    inherit: rycerz
    name: Paladyn
    max_mana_regeneration: 6
    mana_regeneration: 5
    mana_max: 125
    mana: 125
    spells:
      - railgun
(...) much more spells
```
This is my upgrade item:
```
paladyn_upgrade:
    icon: gold_sword:1 # does not apply
    upgrade: true
    hidden: true
    hotbar_count: 3
```
The thing is after buying all needed spell and upgrade, `hotbar_count:3` is applied, but icon not, also wanted to change `Name` and `Description`, but they're not applied either.

MC Version: Spigot 1.13.2
Magic Version: Magic-7.6.17

**Comment by NathanWolf** [comment]
Since upgrades are actually items they have their own icon/name/description that they use, and you don't always want those to transfer to the item being upgraded. So there are 3 special properties for when you do:

```
paladyn_upgrade:
  upgrade_icon: gold_sword:1
  upgrade_name: Paladyn Wand
  upgrade_description: It is super awesome
```
