### ISSUE TITLE
"horse" spell allowing clipping through walls

### ISSUE THREAD

**Issue by Ferocimo** [elBukkit/MagicPlugin#452]
Hello,

Spawning a horse "on" a wall will make it spawn "inside" the wall. Then, mounting it will allow the player to pass through the wall.

Ideally there should be a protection that prevents a horse from spawning too near a wall.

Thank you.

**Comment by NathanWolf** [comment]
Sounds hard... you could maybe use a Volume + CheckBlock action though.

Just FYI, since you've been making a ton of bug reports / requests recently- no one is really actively working on this plugin right now. If that's going to be an issue then you may want to look for other plugins (e.g. MagicSpells) - sorry!

It's just me here and I don't have the time. I am usually willing to stop and fix critical bugs, but stuff like spell configs I am probably not going to get to anytime soon.

**Comment by Ferocimo** [comment]
@NathanWolf I must admit I have no idea how to configure the spell so it checks wall proximity with checkblock and volume. Most of the time when I "made" or reworked spells you created, I just used bits of other stuff you've done.

**Comment by Ferocimo** [comment]
@NathanWolf If you have a bit of extra time, could you tell me how I could do that ?

**Comment by NathanWolf** [comment]
Try something like this at the start of the spell's actions

```
actions:
  cast:
    - class: ChangeContext
       target_offset: 0,1,0
       actions:
      - class: Disc
         radius: 2
         actions:
         - class: CheckBlock
            allowed: air
     - class: SpawnEntity // This is where the original horse actions go ...
```

This will cancel the spell if any block in a 2-block radius around the target is non-air... I think. I'm not sure you're going to be able to come up with something that covers all of the cases, though.
