### ISSUE TITLE
Brooms not leveling

### ISSUE THREAD

**Issue by Curtis73** [elBukkit/MagicPlugin#477]
Sorry to be a pain, but it appears that brooms aren't levelling up properly. For some of my players, it's not levelling up past level two, but it's not going past level one for me when I tried it. I thought that it could be that `upgrade_required_path` isn't in levels 2-5, but I added it and still nothing, and I'm not sure if this is user error or something in the code.
Firebolt:
```
firebolt:
    mode: cast
    path: broom
    active_spell: broom
    migrate_icon: gold_barding
    icon: wood_hoe:29
    indestructible: true
    undroppable: true
    bound: true
    keep: true
    effect_color: 'FF00FF'
    overrides: broom.mount_boost 1.5, broom.mount_boost_ticks 140, broom.mount_health 20, broom.steer_speed 0.7, broom.slow_steer_speed 0.6, cancel_on_damage 0.5
    spells:
        - broom
```
Broom spell:
```
broom:
    category: Brooms
    upgrade_required_path: broom
    upgrade_required_casts: 20
    parameters:
        sound: magic.flying
        sound_max_volume: 20000
        sound_min_volume: 1000
        sound_max_pitch: 2
        sound_min_pitch: 0.5        
broom|2:
  upgrade_required_casts: 30
  parameters:
    steer_speed: 0.05
    max_speed: 1.25
    max_acceleration: 0.015
    duration: 75000
    cooldown: 13000

broom|3:
  upgrade_required_casts: 40
  parameters:
    steer_speed: 0.07
    max_speed: 1.5
    max_acceleration: 0.02
    duration: 90000
    cooldown: 10000

broom|4:
  upgrade_required_casts: 50
  parameters:
    steer_speed: 0.1
    max_speed: 1.75
    max_acceleration: 0.03
    duration: 100000
    cooldown: 9000

broom|5:
  upgrade_required_casts: 50
  parameters:
    steer_speed: 0.5
    max_speed: 2
    max_acceleration: 0.04
    duration: 120000
    cooldown: 8000
```
