### ISSUE TITLE
Is there any way to make wands drop on death?

### ISSUE THREAD

**Issue by bamboocityguy** [elBukkit/MagicPlugin#483]
On a survival server, and I figured the intense power of magic would be balanced by the possibility that you just lose it all one day, but I see that you spawn each time with your wand; any way to make it drop like any other item?

**Comment by NathanWolf** [comment]
In plugins/Magic/wands.yml
```
base_bound:
  keep: false
```

**Comment by NathanWolf** [comment]
Actually, better do all of this:
```
base_bound:
  bound: false
  keep: false
  invulnerable: false
  immortal: false
  track: false
```
