### ISSUE TITLE
Other Cooldown Display Methods

### ISSUE THREAD

**Issue by mibby** [elBukkit/MagicPlugin#485]
I have some wands with very high cooldowns configured. They do not use any mana, as they are a single use spell with a 3-5 minute cooldown. However for the life of me, I cannot figure out how to output in chat or action bar when a cooldown has lapsed and the spell is ready to be used again.

**Comment by NathanWolf** [comment]
I don't there is a way to do that, unfortunately. I'll keep this open as a feature request but it's kind of a challenge honestly, it's not how cooldowns work. There is no task or timer constantly checking all of your spells to see if a cooldown is up- it only checks when you try to cast a spell.

**Comment by mibby** [comment]
Okay, thanks for the consideration in any case!

--

Side question; is there any way to have custom lore & auto-generate descriptions on a wand? I tried using some variables like $description but it didn't seem to do anything. Specifically, I'm trying to have a wand with lore describing the spells on it (left/right click) while retaining info such as cooldown, range, warmup, etc. Even moreso, when a wand has 2 different spells included on it for different primary and alternate use, it no longer includes this information even if they retain the same cooldown and range.

**Comment by martdamp** [comment]
You could try using the Chat Action to send a msg after a certain delay. This can be done by having the delay action, then the chat action and having the cooldown set to 0. I would prefer to create a second move which has the delay and the chat action and use the Cast Action to cast that spell.

**Comment by NathanWolf** [comment]
The custom lore thing should be possible, yes.

Something like this?
```
customlore:
  inherit: wand
  lore:
  - This wand has
  - completely
  - custom
  - lore
  - $owner
  - You can add variables like so
  - $description
  - $spells
  - $brushes
  - $mana_regeneration
  - $path
  - $mana_max
```
