### ISSUE TITLE
Alternate Down Not Working for Gather Spell

### ISSUE THREAD

**Issue by mercurialmusic** [elBukkit/MagicPlugin#486]
Very possibly something I'm doing wrong, but also potentially a bug. With the Gather upgrade, the `alternate_down_parameters` don't seem to be working, and instead it casts the regular spell with tpa instead of tpahere. 

We do use a slightly modified version of the spell (below), altering the command so that it works with our teleport system, but since the modifications work with the regular Gather spell I would have figured they should also work for tpahere.

We had been using the latest release (7.6.19) and experiencing the issue, but updated to the 7.6.20 snapshot (b2853 I think) since I saw some alt-cast parameter tweaks in the changelog, but still no dice. Using CraftBukkit version git-Spigot-cf694d8-8d8475f (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT).

Thanks for any help!

```yml
gather:
  icon: diamond_axe:48
  icon_disabled: diamond_hoe:48
  icon_url: http://textures.minecraft.net/texture/ff78194bb5fe3f374ca6a1727c04247b7bac331cff248bf642acc8e73647e
  category: master
  tags: noduel,nojail
  worth: 15
  show_undoable: false
  upgrade_required_path: student
  upgrade_required_casts: 20
  actions:
    cast:
    - class: PlayerSelect
      actions:
      - class: Command
  effects:
    cast:
    - class: EffectSingle
      sound: entity_player_levelup
    player_selected:
    - class: EffectSingle
      sound: entity_endermen_ambient
    - class: EffectTrail
      particle: portal
      particle_count: 4
    - class: EffectSingle
      location: both
      effectlib:
        class: WarpEffect
        particle: portal
  parameters:
    target: none
    command: cmi tpa @tn
    target_self: false
    cooldown: 30000
    bypass_friendly_fire: true
    bypass_pvp: true
  costs:
    mana: 50
gather|2:
  alternate_down_parameters:
    command: cmi tpahere @tn
```

**Comment by NathanWolf** [comment]
You may need to rename the spell, if you still have the default configs loading. Alternately, try putting `inherit: false` in the config. I think the base gather spell is interfering.  I tried a simpler test and it seems fine:

```
gather2:
  icon: diamond_axe:48
  icon_disabled: diamond_hoe:48
  icon_url: http://textures.minecraft.net/texture/ff78194bb5fe3f374ca6a1727c04247b7bac331cff248bf642acc8e73647e
  category: master
  tags: noduel,nojail
  worth: 15
  show_undoable: false
  upgrade_required_path: student
  upgrade_required_casts: 20
  actions:
    cast:
    - class: Command
  effects:
    cast:
    - class: EffectSingle
      sound: entity_player_levelup
    player_selected:
    - class: EffectSingle
      sound: entity_endermen_ambient
    - class: EffectTrail
      particle: portal
      particle_count: 4
    - class: EffectSingle
      location: both
      effectlib:
        class: WarpEffect
        particle: portal
  parameters:
    target: none
    command: say Hi
    target_self: false
    cooldown: 30000
    bypass_friendly_fire: true
    bypass_pvp: true
  costs:
    mana: 50

gather2|2:
  alternate_down_parameters:
    command: say Hi 2
```

**Comment by mercurialmusic** [comment]
Hmm. Thanks for the suggestions. I tried renaming, using the inherit: false, and disabling the default gather spells (both the regular and the upgrade) after renaming, just to be sure. 

```
gather2:
  name: 'Gather'
  inherit: false
  icon: diamond_axe:48
  icon_disabled: diamond_hoe:48
  icon_url: http://textures.minecraft.net/texture/ff78194bb5fe3f374ca6a1727c04247b7bac331cff248bf642acc8e73647e
  category: master
  tags: noduel,nojail
  worth: 15
  show_undoable: false
  upgrade_required_path: student
  upgrade_required_casts: 20
  actions:
    cast:
    - class: PlayerSelect
      actions:
      - class: Command
  effects:
    cast:
    - class: EffectSingle
      sound: entity_player_levelup
    player_selected:
    - class: EffectSingle
      sound: entity_endermen_ambient
    - class: EffectTrail
      particle: portal
      particle_count: 4
    - class: EffectSingle
      location: both
      effectlib:
        class: WarpEffect
        particle: portal
  parameters:
    target: none
    command: cmi tpa @tn
    target_self: false
    cooldown: 30000
    bypass_friendly_fire: true
    bypass_pvp: true
  costs:
    mana: 50
gather2|2:
  name: 'Gather'
  inherit: false
  alternate_down_parameters:
    command: cmi tpahere @tn
```

Then I also tried your example, with the say command on the upgrade spell:
```
gather2|2:
  name: 'Gather'
  inherit: false
  alternate_down_parameters:
    command: say Hi
```

Both attempts had the same results - the spell kept running the regular tpa instead of the alternate command. It seems it's just not recognizing the downward look. Which is weird because the same downward look works for the recall marker placement.
