### ISSUE TITLE
How do I change spell times?

### ISSUE THREAD

**Issue by Rhinoatron** [elBukkit/MagicPlugin#488]
I've been wondering this for weeks now, how do I change how long a spell can last? Like silence, for instance, change that to like 10 minutes?

**Comment by killme** [comment]
https://github.com/elBukkit/MagicPlugin/blob/17a09aa83deefc8822e80183712681cdadd2b03d/Magic/src/main/resources/examples/survival/spells/silence.yml#L54

You should be able to create a file `spells/silence.yml` as follows to change this value:
```yml
silence:
    parameters:
        duration: 600000
```
