### ISSUE TITLE
External command spell?

### ISSUE THREAD

**Issue by jamesol1** [elBukkit/MagicPlugin#490]
It seems that the command spell doesn't work with external commands? I'm planning on using magicspells alongside magic (i have a lot of magicspells based spells i want to use<--- most of which i cant remake in magic).  
https://pastebin.com/XQtQfBLJ
Here is the spell i've made. I've tried messing around with adding self targetting, other ways of formatting the command: line etc. It just doesn't seem to work. 

If one does not exist, could a external command action be made? 

Many thanks.

**Comment by NathanWolf** [comment]
I'm not sure what you mean by an "external" command, but the Command action can run any command the player can run. Do they have permission for /magicspellcast? 

It can also run commands as console if magicspells has some way to use the command on behalf of the player, so they don't need permission to run the command themselves.

**Comment by jamesol1** [comment]
Hi Nathan,
The command works perfectly fine typing it in game. I'm currently OP'd so it shouldnt be a perm issue. It's just getting the spell to play out the command. By external i just meant outside of the plugin magic and vanilla commands.

**Comment by NathanWolf** [comment]
That's exactly what this action is for, there's no reason you'd really ever want to have it use a command from Magic.

I don't know what the problem would be then. Try `/mage debug 20` and then `/cast Fly` and see what shows up in chat.

**Comment by jamesol1** [comment]
![image](https://user-images.githubusercontent.com/24861741/56072747-e3807b00-5d91-11e9-8343-b46489e26136.png)
This is what came up. Bare in mind /cast fly actually performs the 'Magic' plugins fly spell, not magic-spells (incase you didn't know).  The fly spell I'm using is from magicspells, i named the command spell fly. You probably know all this but i'm just clarifying.

**Comment by NathanWolf** [comment]
Maybe try it with something like /say or some other simple command. It's really pretty simple, and last I checked it worked- you could also try `/cast respawn` which is a builtin spell that looks almost identical to yours

```
respawn:
    hidden: true
    icon: compass
    category: utility
    worth: 50
    actions:
        cast:
        -  class: Command
    effects:
        cast:
        -  class: EffectSingle
           sound: block_portal_travel
           location: both
           effectlib:
             class: WarpEffect
             particle: portal
    parameters:
        command: spawn
        op: true
        target: none
        cooldown: 30000
```

If none of that gets you anywhere I will try to run your spell with a different command when I can, but I haven't really been actively working on this plugin in a while so it may not be right away.
