### ISSUE TITLE
Multiple Issues and Questions

### ISSUE THREAD

**Issue by leveljaap** [elBukkit/MagicPlugin#525]
Hello,

I tried to change the display names of the "Beginner", "Student", "Apprentice" and "Master" paths but I couldn't figure out how to do it. Can you help me?

As additional question, I wondered in what format vanilla attributes of entities should be provided. Is it possible to put them in a vanilla team when spawning them through spells?

EDIT:
Also, an actual issue, Growth doesn't work on other crops than wheat. (Potatoes, carrots, etc.)

EDIT2:
ANOTHER issue, I can't seem to change the health of a mob. I thought this was done by changing the value of ```max_health``` but that doesn't do anything. Am I doing something wrong here?

EDIT3:
I'm sorry for all the questions but I was also wondering how I could make only one axis of the Velocity spell class dependant on rotation of the caster. So like a Fling spell that only works horizontally.

**Comment by NathanWolf** [comment]
For path names, put something like this in messages.yml

```
paths:
    beginner:
        name: "&7Beginner"
        description: Just starting out with magic
    student:
        name: "&2Student"
        description: Starting to learn the basics
... etc
```

The defaults for this can be found here:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/examples/survival/messages/paths.yml

I will need to look into Growth, guessing something changed with block states in 1.13 and it's been broken for a while.

For magic mobs there is just a `health` property. You can see the default mob configs here:

https://github.com/elBukkit/MagicPlugin/tree/master/Magic/src/main/resources/examples/survival/mobs

The same goes for spells that spawn mobs.

For the Velocity action, I'm not positive but try adding `direction: 0,1,0` to your spell config.
