### ISSUE TITLE
Line radius or Cylinder modification

### ISSUE THREAD

**Issue by malonnnn** [elBukkit/MagicPlugin#543]
So to cut a long story short:

I'm trying to make a thick laser beam (called a Kamehameha, reference here: https://i.ytimg.com/vi/Zq1aPOunsFA/maxresdefault.jpg)

My initial idea was to use a Line but set a radius, but it does not have a radius feature.

My next idea was to use a cylinder and have the cylinder draw away from the player, along the eyesight vector like Line, but cylinder doesn't seem to be able to do that.

The request:
Please allow line to have a radius, or allow cylinder to be "pointed".

Thank you!

**Comment by malonnnn** [comment]
Is this something likely to be added? I check this post like every day hoping someone leaves some kind of comment, and pretty much every other issue has some comment, which is fair considering they are reporting bugs and mines a feature request.

At any rate, I would really, really, really like this feature (preferably an aimable cylinder)

**Comment by NathanWolf** [comment]
Hey, I was hoping to test some things out before replying to see if this is doable. I was trying to do something similar a while back, but I never could get it working. I thought maybe we had added something, but I'm not sure.

The problem here is that this is not really a Magic request exactly, it is an EffectLib request. And I am not really good with EffectLib. I just maintain it, but the math is all due to the original author who left the project many years ago.

So I would say, yes, it's a possibility- but it may be kind of unlikely. At this point the focus for Magic is really on bug and exploit fixes, and version compatibility. EffectLib is effectively in maintenance, it hasn't been touched at all since before the 1.13 release.

**Comment by malonnnn** [comment]
I actually didnt realize that effectslib was unmaintained...

Thank you for this reply, it's very enlightening

**Comment by malonnnn** [comment]
I could really use this feature, so I'm willing to pay for it. I attempted to look through the code, but I'm just too unfamiliar with java in general to really understand what's happening.

I know you say you're not great at the math, but if you would be willing to give this a shot, I would be hugely appreciative. I'm happy to make a sizeable donation of what you think this effort is worth. I am even willing to pay up front if you believe it is a fake offer, I just would _really_ _really_ like this feature.

**Comment by malonnnn** [comment]
@NathanWolf 

Would you be willing to point me in the direction of where you think the modifications would need to be implemented? I can't seem to find the cylinder or line code. I am going to attempt it myself and maybe make a pull request if I get it, if I could just find where I need to start making alterations. Thank you

**Comment by NathanWolf** [comment]
Sorry I never responded- I would like to give this a shot, but doubt I will have time.

I actually think it's something I tried before, and failed...

The code is in EffectLib, so you'd have to make a PR there:

https://github.com/Slikey/EffectLib/blob/master/src/main/java/de/slikey/effectlib/effect/CylinderEffect.java

**Comment by malonnnn** [comment]
Fast response, thank you. I'm considering posting a bounty for this on some math forum somewhere. There's gotta be someone somewhere who can do this, if I can't.

**Comment by NathanWolf** [comment]
I think I will have what you want in the next dev build. Here is an example:

```
cylinder:
    effects:
        cast:
           - class: EffectSingle
             location: origin
             relative_offset: 2,0,0
             effectlib:
                 update_locations: false
                 update_directions: false
                 class: CylinderEffect
                 particle: redstone
                 radius: 0.6
                 height: 5
                 enable_rotation: false
                 particles: 100
                 duration: 1000
                 period: 1
                 offset: 0,-0.1,0
                 orient: true
```
The new thing is "orient", which will make the cylinder align to the player's facing.

The only tricky part is that it is still centered on the source location, but you can use relative_offset to move it out away from the player.

Hope this works for you!
