### ISSUE TITLE
Using the TeleportAction to get through the World Border

### ISSUE THREAD

**Issue by martdamp** [elBukkit/MagicPlugin#563]
I created a move that lets a player "Dash" and it uses the TeleportAction. However when you use it next to the World Border the player can get through it. I created a test move which recreates this issue:
```
test_teleport:
    actions:
        cast:
        -   class: Teleport
    parameters:
        allow_max_range: true
        allow_passthrough: false
        range: 10
        vertical_range: 2
        safe: false
        transparent: transparent_no_water
        target: block
```

**Comment by NathanWolf** [comment]
Try adding `world_border_restricted: true` at the top level (not under parameters)

**Comment by martdamp** [comment]
Adding that doesn't work for me. We are on magic version 7.6.20 so that shouldn't be the problem.
```
test_teleport:
    world_border_restricted: true
    actions:
        cast:
        -   class: Teleport
    parameters:
        allow_max_range: true
        allow_passthrough: false
        range: 10
        vertical_range: 2
        safe: false
        transparent: transparent_no_water
        target: block
```
