### ISSUE TITLE
Feature Suggestion- CheckPermissions Action

### ISSUE THREAD

**Issue by KingofAnomaly** [elBukkit/MagicPlugin#584]
I need this feature to make an approval rating and quest GUI on my server where I can enable and disable spells via other spells.

**Comment by NathanWolf** [comment]
You can do this with the CheckRequirements action, like this:

```
approved:
  actions:
    cast:
      - class: CheckRequirements
        requirements:
          - permission: approved
      - class: Message
        message: You are OK!
```
