### ISSUE TITLE
Wand overrides not overriding command string.

### ISSUE THREAD

**Issue by mibby** [elBukkit/MagicPlugin#611]
Magic dev 2913
Paper dev 226 (Spigot 1.14.4)

Spell
```
magichat:
    icon: spell_icon:138
    icon_disabled: spell_icon_disabled:138
    hidden: true
    icon_url: http://textures.minecraft.net/texture/2abee4fe341011b9a0ae2fb83644f695521fd4e4c6198fe23112f1acbf38369
    category: utility
    worth: 100
    actions:
      cast:
      - class: Delay
        delay: 1
      - class: Hat
      - class: Command
    effects:
      cast:
      -  class: EffectSingle
         location: target
         effectlib:
           class: SphereEffect
           iterations: 4
           particle: smoke_large
    parameters:
      target_self: true
      use_item: true
      reason: custom
      cooldown: 1000
      range: 1
      allow_max_range: true
      command: lp user @uuid permission set hat.example
      console: true
```

Wand
```
base_hat:
    mode: cast
    active_spell: magichat
    indestructible: true
    locked: true
    keep: true
    bound: true
    effect_color: '888888'
    spells:
        - magichat
hat_1:
    name: Hat 1
    icon: diamond_shovel:41
    inherit: base_hat
    overrides: magichat.command lp user @uuid permission set hat.1
```

When I try to use the hat_1 item, it does not grant the permission ``hat.1``. It is granting the permission ``hat.example`` from the spell. Do command overrides not work?

Similarly, when typing ``/wand override`` while holding the wand, it cuts off after the first space of the command. It does not show the full command in-game.
