### ISSUE TITLE
Problem with Smite (lightning) spell

### ISSUE THREAD

**Issue by Blamo27** [elBukkit/MagicPlugin#64]
We have a problem with the spell Smite : players can't cast this spell because they haven't got the permission to cast it in an area that doesn't allow them to build. In other terms, where they can't build, they can't cast the spell. 

This include, for instance, warzone claims and WorldGuard protected arenas. 
We can't deactivate the "region manager" because we still need it for other spells, we just want to know how we can allow players to use this specific spell in protected areas.

**Comment by NathanWolf** [comment]
You can add the following to spells.yml if you'd like players to be able to break/build blocks in regions where they don't have permission to do so by hand:

```
smite:
  parameters:
     bypass_build: true
     bypass_break: true
```

Alternately, if you have WGCustomFlags you can add the spells to the allowed-spells flag in specific regions.

**Comment by Blamo27** [comment]
Oh, I'll try thanks you !

**Comment by Blamo27** [comment]
Not working with factions :/

**Comment by NathanWolf** [comment]
Hm- it should .. I actually didn't think it'd block in a Warzone in general, it should only deny perms in faction bases. But those bypass params skip all the checks anyway- I guess could you paste that spell config here? Or is it exactly what I wrote up there?

**Comment by Blamo27** [comment]
Yes the config :

```
lightning:
    alias: storm
    upgrade_required_path: apprentice
    upgrade_required_casts: 50
    icon: raw_fish:2
    icon_url: http://textures.minecraft.net/texture/c0d34b6c68eca9dae0f9dabeadeb5f72536fa20ab4ecf669be895baf1c17
    category: elemental
    pvp_restricted: true
    worth_sp: 300
    earns_sp: 2
    actions:
        cast:
        -  class: Spread
           actions:
           -  class: Lightning
    effects:
        cast:
        -  class: EffectSingle
           sound: firework_large_blast
        -  class: EffectTrail
           particle: smoke_normal
           particle_count: 2
        -  class: EffectSingle
           location: target
           effectlib:
             class: HelixEffect
             particle: smoke_normal
             iterations: 3
    parameters:
        bypass_build: true
        bypass_break: true
        target_type: LivingEntity
        allow_max_range: true
        range: 32
        radius: 8
        cooldown: 10000
    costs:
        mana: 80
```
