### ISSUE TITLE
1.15.2 Target Selectors Don't Work

### ISSUE THREAD

**Issue by alexis-evelyn** [elBukkit/MagicPlugin#643]
The selectors @td, @t, @tn, and @tuuid do not resolve to anything on 1.15.2 Paper. Everything else like @uuid, @tz, and so on works perfectly fine. There are no errors in console or in chat.

Edit: Magic Version is Magic 7.8.1-ee5f66c

**Comment by alexis-evelyn** [comment]
The spell I tested with is:
```
slashkill:
  icon: spell_icon:48
  icon_disabled: spell_icon_disabled:48
  icon_url: http://textures.minecraft.net/texture/ff78194bb5fe3f374ca6a1727c04247b7bac331cff248bf642acc8e73647e
  enabled: true
  hidden: true
  cancellable: true
  cast_on_no_target: false
  actions:
    cast:
    - class: CustomProjectile
      actions:
      - class: Command
  parameters:
    target: none
    command: say minecraft:kill @spell, @pd (caster display name), @p, @pn (same as @p, caster name), @uuid, @world, @x, @y, @z, @tworld, @tx, @ty, @tz (target location), @td (target display name), @t, @tn (same as @t, target name), @tuuid
    target_self: false
    cooldown: 0
  effects:
    cast:
    -  class: EffectSingle
       sound: magic.zap_crack
       location: origin
       color_override: color
       effectlib:
         class: ConeEffect
         iterations: 10
         particle: redstone
         lengthGrow: 0.1
         radiusGrow: 0.003
         updateLocations: false
         updateDirections: false
         particle_count: 8
         particle_offset_y: 0.1
         particle_offset_x: 0.1
         particle_offset_z: 0.1
```
