### ISSUE TITLE
ModifyEntity Actions Destroys Magic Mob Data

### ISSUE THREAD

**Issue by NeoFalcon1605** [elBukkit/MagicPlugin#751]
```
truepolymorph:
  icon: snowball
  actions:
    cast:
      - class: ModifyEntity
  parameters:
    target: other
    range: 32
    delay: 5000
    type: husk
```

Using modify entity to change the mob type causes the entity to lose all magic properties
