### ISSUE TITLE
Wrong costs at shop

### ISSUE THREAD

**Issue by Elsopeen** [elBukkit/MagicPlugin#77]
Hello, 
I changed the worth of items in the spell "magicitemshop" but every price is not what I defined.
Here is the worths I configured in the "spells.yml" file:
magicitemshop:
    parameters:
        use_items: true
        items:
        - item: wand|camera
          cost: 14
        - item: none
        - item: wand|ocarina
          cost: 10
        - item: hylian_shield
          cost: 75
        - item: wand|goggles
          cost: 14
        - item: wand|divinghelmet
          cost: 25
        - item: wand|magichat
          cost: 30
        - item: none
        - item: none
        - item: none
        - item: wand|wizardhelmet
          cost: 40
        - item: wand|wizardchestplate
          cost: 40
        - item: wand|wizardleggings
          cost: 40
        - item: wand|wizardboots
          cost: 40
        - item: wand|apprenticehelmet
          cost: 2
        - item: wand|apprenticechestplate
          cost: 2
        - item: wand|apprenticeleggings
          cost: 2
        - item: wand|apprenticeboots
          cost: 2
        - item: none
        - item: wand|rabbitboots
          cost: 120
        - item: wand|rocketboots
          cost: 250
        - item: wand|hulkboots
          cost: 100
        - item: wand|flashboots
          cost: 150
        - item: wand|clericchestplate
          cost: 250
        - item: wand|magneticleggings
          cost: 500
        - item: none
        - item: none
        - item: none
        - item: none
        - item: none
        - item: none
        - item: wand|invisiblecloak
          cost: 120

And here is a screenshot of what I get :
![2016-04-03_15 09 55](https://cloud.githubusercontent.com/assets/16364961/14232558/56c3d1de-f9ae-11e5-958f-77e81cb388e2.png)

I hope you'll can help me in this problem, because it can ruin our economy system...
Waiting for your answer,
Best regards,
Elsopeen

**Comment by NathanWolf** [comment]
If you're going to use dev builds, make sure to check the changelog!

Specifically, there's this:

 - Default emerald worth changed to 100 to make Vault-less economy less expensive

Previously default prices were through the roof when using emeralds.

Changing this back is easy, just adjust this section from config.yml:

```
# By default the Magic ecnonomy is balanced towards a typical Vault economy
# If Vault is not present, Magic falls back to a physical, emerald-based ecnonomy.
# For balancing purposes, an emerald will be considered worth 100 "vault dollars" by default.
# This scales all of the prices down when using emeralds.
#
# Adjust the "worth" value below to scale an item-based economy up or down. A value of 1 will make
# emerald costs match configured worth/cost values.
currency:
  emerald:
    worth: 100
    name: Emerald
    name_plural: Emeralds
```
