### ISSUE TITLE
Adjusting OtherSide mobs 

### ISSUE THREAD

**Issue by TheDarthFather** [elBukkit/MagicPlugin#826]
The number of endermans that spawn on the other side is killing my NAS cpu :).
How can I adjust the freqvence of each "mod replace" ?

I assume is here, but I dont see a reasoon for so many enderman replacements ...  https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/examples/otherside/worlds/otherside_mobs.yml 

Also .. is Magic overridding  my paper config mob limits ?

**Comment by NathanWolf** [comment]
In the “fallback” rule you can see the vast majority (about 10x the next mob) of mobs are replaced with enderman. It’s supposed to be the home dimension of enderman, so there _should_ be a ton of them there, similar to the end.

I do not know how the paper mob limits work, but I would not be surprised if replacing mobs breaks them since Paper doesn’t really know what kind of mob is ultimately going to be spawned.

So you could try reducing the probability there, but I suspect there is some larger problem and you’ll just get a lot of other mobs but still have more than you want.

Does this only happen in your spawn chunks, or does it look like this everywhere in that world?

**Comment by TheDarthFather** [comment]
I did not test more than what I did last time (spawn) .. as my server was very laggy.
I will try again ...so: 
I will need to change this:
`enderman: 1000`
to this:
`enderman: 10`

Also ... below ... I see the probability (assume 0.9 = 90%) ... 
`warlock: 10` means ? 10% out of that 90% ?

```
rabbit:
      class: Replace
      target_type: rabbit
      probability: 0.9
      replace_type:
        warlock: 10
        dark_wizard: 1
        killer_bunny: 20

```
