### ISSUE TITLE
specific block target peramaters?

### ISSUE THREAD

**Issue by zacharyki102** [elBukkit/MagicPlugin#839]
believe me I have tried to find it but as far as I can tell there is no way to have a spell target a specific block. Example: have a spell only activate if it hits glass to shatter it or enchant a campfire to heal people around it? while I imaging that this feature does exist but if so I haven't been able to find it.

**Comment by NathanWolf** [comment]
You can use the CheckBlock action for this- like
```
actions:
  cast:
    class: CheckBlock
    allowed: campfire
    actions:
         - class: AreaOfEffect
            actions:
            - class: PotionEffect
```
