### ISSUE TITLE
Customize server

### ISSUE THREAD

**Issue by Xzeajan** [elBukkit/MagicPlugin#95]
Today I installed magic and am really excited to put it online! But I cannot find some example configs (or the edits I tried to make, crashed magic)

Anyone can help me with the following:
-All crafting recipes disabled, only possible to get a wand, with /wand beginner 
(using commandchest to activate OP commands for emeralds)
-the beginner wand needs some more mana to be casting more expensive spells
-No other wands in the game available, nowhere except for admins.
-Wands cannot be upgraded or combined
-Spells can be added, only through /wand add <spell>
(also commandchest to activate OP commands)
-Beginner wand's magic missle, some damage increase?

Everytime I try to put this in the config, my server crashes. Anyone got some help?

**Comment by NathanWolf** [comment]
Put this in config.yml:
```
enable_crafting: false
enable_enchanting: false
sp_enabled: false
enable_automatic_spell_upgrades: false
```

In wands.yml:
```
wand:
    mana_max: 100
    mana: 100
    mana_regeneration: 20
```

And this in spells.yml:
```
missile:
 parameters:
        player_damage: 4
        entity_damage: 8
```
