### ISSUE TITLE
Netherbiome Bug

### ISSUE THREAD

**Issue by ookami0104** [elBukkit/MagicPlugin#986]
I'm Japanese and I'm using a translator, so the text may not be correct, but please help me!

When I use a skill called "nether biome", it turns into a nether on a large scale and I don't know how to bring it back.

I've managed to convert the biome with worldsets, but is there any other way to get it back?

**Comment by NathanWolf** [comment]
Is the spell "netherize" from the "netherside" example?

If so your best is probably to use Rollback, that is a spell from the engineering example. You can either add that example if you don't have it already, or just install that one spell.

`/mexample add engineering`
`/wand add rollback`

Casting rollback at the modified blocks should restore them.

**Comment by ookami0104** [comment]
Rollback was not possible.
Here is the magic I used.
![image](https://user-images.githubusercontent.com/80665012/140802447-192aaf69-21cc-439f-a5af-11c35f2d36ae.png)

**Comment by NathanWolf** [comment]
Oh yeah literally changing the biome ...

There will be no way to undo that properly. Your only recourse is to reset the biomes on all effected blocks to something else. Here's an example using plains:

```
resetbiome:
  icon: stone_pickaxe{CustomModelData:18001}
  icon_disabled: stone_pickaxe{CustomModelData:18002}
  actions:
    cast:
      - class: Sphere
        actions:
          - class: ChangeBiome
  parameters:
    target: block
    allow_max_range: false
    range: 32
    radius: 128
    type: sphere
    check_destructible: false
    biome: plains
```
You can copy that into a file in your spells folder if you want.
